---
# These tasks configure the specific items for the
# Netmaker EE Edition

- name: Get the docker compose file for netmaker
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/gravitl/netmaker/\
          {{ netmaker_version }}\
          /compose/docker-compose.ee.yml"
    dest: "{{ netmaker_directory }}/docker-compose.yml"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: 0644
  when: netmaker_version != netmaker_version_installed
  notify: Restart Netmaker

- name: Replace the default values in the docker-compose file
  ansible.builtin.replace:
    path: "{{ netmaker_directory }}/docker-compose.yml"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - regexp: "REPLACE_SERVER_IMAGE_TAG"
      replace: "{{ netmaker_version }}"
    - regexp: "REPLACE_UI_IMAGE_TAG"
      replace: "{{ netmaker_version }}"
    - regexp: "NETMAKER_BASE_DOMAIN"
      replace: "{{ netmaker_base_domain }}"
    - regexp: "SERVER_PUBLIC_IP"
      replace: "{{ ansible_default_ipv4.address }}"
    - regexp: "REPLACE_MQ_USERNAME"
      replace: "{{ netmaker_mq_username }}"
    - regexp: "REPLACE_MQ_PASSWORD"
      replace: "{{ secret_nm_mq_password }}"
    - regexp: "YOUR_LICENSE_KEY"
      replace: "{{ secret_nm_license_key }}"
    - regexp: "YOUR_ACCOUNT_ID"
      replace: "{{ secret_nm_account_id }}"
  notify: Restart Netmaker

- name: Overwrite config file locations in docker-compose file
  ansible.builtin.replace:
    path: "{{ netmaker_directory }}/docker-compose.yml"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - regexp: "/root/mosquitto.conf"
      replace: "{{ netmaker_directory }}/mosquitto.conf"
    - regexp: "/root/wait.sh"
      replace: "{{ netmaker_directory }}/wait.sh"
    - regexp: "/root/Caddyfile"
      replace: "{{ netmaker_directory }}/Caddyfile"
  notify: Restart Netmaker

- name: Get the Caddyfile file for netmaker
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/gravitl/netmaker/\
          {{ netmaker_version }}\
          /docker/Caddyfile-EE"
    dest: "{{ netmaker_directory }}/Caddyfile"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: 0644
  when: netmaker_version != netmaker_version_installed
  notify: Restart Netmaker
