---
# Install the netclient

# Create the netclient directory
- name: Create the netclient directory
  ansible.builtin.file:
    path: "{{ netclient_directory }}"
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0766'

# Write the netclient docker-compose file
- name: Write the netclient docker-compose file
  ansible.builtin.template:
    src: docker-compose-netclient.yml.j2
    dest: "{{ netclient_directory }}/docker-compose.yml"
    mode: 0666

# Get the enrollment key for the netclient
# Get the latest enrollment keys
- name: Get the latest enrollment keys
  ansible.builtin.command:
    cmd: "nmctl enrollment_key list -o json"
  register: nm_enrollment_key_list
  changed_when: false

# Debug the nm_enrollment_key_list variable
- name: Debug the nm_enrollment_key_list variable
  ansible.builtin.debug:
    msg: "{{ item.token }}"
  loop: "{{ nm_enrollment_key_list.stdout | from_json }}"
  when: "'all-networks' in item.tags"
