---
# Install the netclient via docker-compose
#
# Required input vars:
#   network_tag: The network to connect to on the Netmaker server. The
#                netclient needs to connect to a network during the initial
#                setup.
#   nc_hostname: The hostname of the netclient. This is the name that is
#                displayed on the Netmaker dashboard.

# Create the netclient directory
- name: Create the netclient directory
  ansible.builtin.file:
    path: "{{ netclient_directory }}"
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0766'

# Get the enrollment key for the suplied network name
- name: Get the enrollment key for the network '{{ network_tag }}'
  ansible.builtin.set_fact:
    nc_enrollment_key: "{{ nm_enrollment_key_list.stdout
                           | from_json
                           | selectattr('tags', 'contains', network_tag)
                           | map(attribute='token')
                           | first }}"
  changed_when: false

# Write the netclient docker-compose file
- name: Write the netclient docker-compose file
  ansible.builtin.template:
    src: docker-compose-netclient.yml.j2
    dest: "{{ netclient_directory }}/docker-compose.yml"
    mode: 0666
  vars:
    - netmaker_token: "{{ nc_enrollment_key }}"
    - netmaker_hostname: "{{ nc_hostname }}"
  notify:
    - Restart Netclient docker-compose
