---
# Install the netclient via docker-compose
#
# Required input vars:
#   nm_token: The netmaker token used to register the netclient.

# Create the netclient directory
- name: Create the netclient directory
  ansible.builtin.file:
    path: "{{ netclient_directory }}"
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0766'

# Write the netclient docker-compose file
- name: Write the netclient docker-compose file
  ansible.builtin.template:
    src: docker-compose-netclient.yml.j2
    dest: "{{ netclient_directory }}/docker-compose.yml"
    mode: 0666
  vars:
    netmaker_token: "{{ nm_token }}"
  notify:
    - Restart Netclient docker-compose
