---
# Use the NMCTL CLI tool to create enrollment keys on the
# Netmaker server as required.

# Get the current list of enrollment keys
- name: Get the current list of enrollment keys
  ansible.builtin.command:
    cmd: "nmctl enrollment_key list -o json"
  register: nmctl_enrollment_key_list
  changed_when: false

# Create the enrollment key if it doesn't exist
- name: Create the enrollment key if it doesn't exist
  ansible.builtin.command:
    cmd: >
      nmctl enrollment_key create
      --tags="{{ item.tags }}"
      --networks="{{ item.networks }}"
      --unlimited={{ item.unlimited }}
  loop: "{{ netmaker_enrollment_keys }}"
  when: item.name not in nmctl_enrollment_key_list.stdout
  changed_when: false
