---
# Use the NMCTL CLI tool to create or update network definitions
# on the Netmaker server.

# Get the current list of networks
- name: Get the current list of networks
  ansible.builtin.command:
    cmd: "nmctl network list"
  register: nmctl_network_list
  changed_when: false

# Create the network if it doesn't exist
- name: Create the network if it doesn't exist
  ansible.builtin.include_tasks: nmctl_network_create.yaml
  vars:
    network_options: "{{ item }}"
    network_command: "create"
  loop: "{{ netmaker_networks }}"
  when: item.name not in nmctl_network_list.stdout

# Update the network if it exists
- name: Update the network if it exists
  ansible.builtin.include_tasks: nmctl_network_create.yaml
  vars:
    network_options: "{{ item }}"
    network_command: "update"
    network_name: "{{ item.name }}"
  loop: "{{ netmaker_networks }}"
  when: item.name in nmctl_network_list.stdout
