---
# Playbook to build the fm container images using docker buildx bake
#
# The vars_prompt section will prompt the user for the required variables. If
# --extra-vars is used, the prompt will be skipped.

- name: Build the fm container images
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/buildx.yaml
  vars_prompt:
    - name: fm_tags_version
      prompt: >
        Enter the version(s) to tag the fm container images with. Can be a comma
        separated list of tags.
      private: false
      default: "latest"
    - name: fm_git_tag
      prompt: "Enter the git tag/branch to build the fm container images from"
      private: false
      default: "HEAD"
    - name: fm_push_images
      prompt: >
        Do you want to push the fm container images to the registry?
        (default is loaded locally)
      private: false
      default: "no"
  tags:
    - fm
    - fm.buildx

  tasks:
    - name: Overwrite the fm_buildx_env_vars with the fm_tags_version
      ansible.builtin.set_fact:
        fm_buildx_env_vars_updated: "{{ fm_buildx_env_vars |
                                        combine({'TAGS': fm_tags_version}) }}"
      tags:
        - fm
        - docker
        - docker.buildx

    - name: Setup Docker Buildx
      ansible.builtin.include_role:
        name: docker_buildx
        tasks_from: setup
      vars:
        docker_buildx_instance_name: "{{ fm_buildx_name }}"
      tags:
        - fm
        - docker
        - docker.buildx

    - name: Build the fm container images
      ansible.builtin.include_role:
        name: docker_buildx
        tasks_from: main
      vars:
        docker_buildx_instance_name: "{{ fm_buildx_name }}"
        docker_buildx_git_repo: "{{ fm_buildx_git_repo }}"
        docker_buildx_git_version: "{{ fm_tag_version }}"
        docker_buildx_bake_file: "{{ fm_buildx_bake_file }}"
        docker_buildx_env_vars: "{{ fm_buildx_env_vars_updated }}"
        docker_buildx_push: "{{ fm_push_images | bool }}"
      tags:
        - fm
        - docker
        - docker.buildx
