---
# Hosts that are proxmox VMs and used for docker hosts

# If adding proxmox VMs to multiple proxmox nodes, the network.ip,
# proxmox_vm.proxmox_node, proxmox_vm.id, and proxmox_vm.name
# must be unique across all proxmox nodes.

all:
  children:
    proxmox_vms:
      hosts:
        docker-01.home.stechsolutions.ca:
          base_docker_install: true
          base_docker_config: true
          base_dotfiles:
            install: true
            dotbot_skip_ssh_authorized_file: false
          network:
            ip: "10.10.5.24"
            gateway: "10.10.5.1"
          proxmox_vm:
            proxmox_node: "{{ groups['proxmox_nodes'][0] }}"
            template_id: 9001
            state: "present"
            id: 352
            name: "{{ inventory_hostname.split('.')[0] }}"
            name_fqdn: "{{ inventory_hostname }}"
            start_onboot: true
            disk_size: 30G
            net0: virtio,bridge=vmbr0
            ipconfig0: "ip={{ network.ip }}/24,gw={{ network.gateway }}"
            cores: 16
            memory: 65536
            balloon: 16384
        docker-02.home.stechsolutions.ca:
          base_docker_install: true
          base_docker_config: true
          base_dotfiles:
            install: true
            dotbot_skip_ssh_authorized_file: false
          network:
            ip: "10.10.5.27"
            gateway: "10.10.5.1"
          proxmox_vm:
            proxmox_node: "{{ groups['proxmox_nodes'][0] }}"
            template_id: 9001
            state: "present"
            id: 354
            name: "{{ inventory_hostname.split('.')[0] }}"
            name_fqdn: "{{ inventory_hostname }}"
            start_onboot: true
            disk_size: 40G
            net0: virtio,bridge=vmbr0
            ipconfig0: "ip={{ network.ip }}/24,gw={{ network.gateway }}"
            cores: 32
            memory: 65536
            balloon: 16384
            virtual_disks:
              - comment: 50 GB disk for tdarr scratch space
                scsi: "scsi1"
                device: "local-thin-pool-ssd1:50,discard=on"
                backup: 0
              - comment: 10 GB disk for docker compose proxy volume
                scsi: "scsi2"
                device: "data:10,discard=on"
                backup: 1
              - comment: 10 GB disk for docker compose tdarr volume
                scsi: "scsi3"
                device: "data:10,discard=on"
                backup: 1
              - comment: 5 GB disk for docker compose vehicle volume
                scsi: "scsi4"
                device: "data:5,discard=on"
                backup: 1
              - comment: 10 GB disk for docker compose prometheus volume
                scsi: "scsi5"
                device: "data:10,discard=on"
                backup: 1
              - comment: 5 GB disk for docker compose file volume
                scsi: "scsi6"
                device: "data:5,discard=on"
                backup: 1
