---
# Hosts that are proxmox VMs and their configuration

# If adding proxmox VMs to multiple proxmox nodes, the network.ip,
# proxmox_vm.proxmox_node, proxmox_vm.id, and proxmox_vm.name
# must be unique across all proxmox nodes.

all:
  children:
    proxmox_vms:
      hosts:
        storage.home.stechsolutions.ca:
          docker_install: false
          dotfiles:
            install: true
            dotbot_skip_ssh_authorized_file: false
          postfix:
            install: true
            relayhost: smtp.mailgun.org:587
            relayhost_username: storage@mg.stechsolutions.ca
            relayhost_password: "{{ secret_postfix_mg_storage_password }}"
          network:
            ip: "10.10.5.26"
            gateway: "10.10.5.1"
          proxmox_vm:
            proxmox_node: "{{ groups['proxmox_nodes'][0] }}"
            template_id: 9001
            state: "present"
            id: 353
            name: "{{ inventory_hostname.split('.')[0] }}"
            name_fqdn: "{{ inventory_hostname }}"
            start_onboot: true
            disk_size: 20G
            net0: virtio,bridge=vmbr0
            ipconfig0: "ip={{ network.ip }}/24,gw={{ network.gateway }}"
            cores: 12
            memory: 20480
            balloon: 4096
            passthrough_disks:
              - comment: 12TB disk for ZFS
                scsi: "scsi1"
                device: "/dev/disk/by-id/ata-ST12000NM0127_ZJV0P7MQ"
                backup: 0
              - comment: 12TB disk for ZFS
                scsi: "scsi2"
                device: "/dev/disk/by-id/ata-ST12000NM0127_ZJV0PGT8"
                backup: 0
              - comment: 8 TB disk for mergerfs
                scsi: "scsi3"
                device: "/dev/disk/by-id/ata-WDC_WD80EMAZ-00WJTA0_1EHUNJ6Z"
                backup: 0
              - comment: 8 TB disk for mergerfs
                scsi: "scsi4"
                device: "/dev/disk/by-id/ata-WDC_WD80EMAZ-00WJTA0_1EHVSEBZ"
                backup: 0
              - comment: 12 TB disk for snapraid parity
                scsi: "scsi5"
                device: "/dev/disk/by-id/ata-WDC_WD120EMFZ-11A6JA0_Z2KZU83T"
                backup: 0
              - comment: 12 TB disk for mergerfs
                scsi: "scsi6"
                device: "/dev/disk/by-id/ata-WDC_WD120EFBX-68B0EN0_5QJRU8GB"
                backup: 0
      vpn.home.stechsolutions.ca:
          docker_install: false
          dotfiles:
            install: true
            dotbot_skip_ssh_authorized_file: false
          network:
            ip: "10.10.5.28"
            gateway: "10.10.5.1"
          proxmox_vm:
            proxmox_node: "{{ groups['proxmox_nodes'][0] }}"
            template_id: 9001
            state: "present"
            id: 355
            name: "{{ inventory_hostname.split('.')[0] }}"
            name_fqdn: "{{ inventory_hostname }}"
            start_onboot: true
            disk_size: 20G
            net0: virtio,bridge=vmbr0
            ipconfig0: "ip={{ network.ip }}/24,gw={{ network.gateway }}"
            cores: 2
            memory: 2048
            balloon: 1024
