---
# Hosts that are proxmox VMs and their configuration

all:
  children:
    proxmox_vms:
      hosts:
        docker-testing:
          network:
            ip: "10.10.5.25"
            gateway: "10.10.5.1"
          proxmox_vm:
            state: "present"
            id: 352
            name: {{ inventory_hostname }}
            disk_size: 10G
            net0: virtio,bridge=vmbr0
            ipconfig0: 'ip={{ network.ip }}/24,gw={{ network.gateway }}}'
            cores: 2
            memory: 4096
