---
- name: Create Netmaker Droplet
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/vault.yaml
    - vars/main.yaml

  tasks:
    - name: Configure DigitalOcean Droplet
      include_role:
        name: digitalocean


# The plays below will only run when the hosts group do_netmaker
# is defined and there is at least one host in the group
- name: Initial Setup of Netmaker Droplet
  hosts: do_netmaker
  gather_facts: false
  vars_files:
    - vars/vault.yaml
    - vars/main.yaml

  tasks:
    # Get the changed status from the droplet creation play
    # The create_user_flag will either be 'true' or 'false'.
    # This is used to determine if the user needs to be created the first time.
    # If the status is not changed, the create_user play will not run.
    #
    # The hostvars['localhost']['dp_result']['results'] list contains
    # a dictionary for each droplet created. The dictionary has the keys
    # 'ansible_loop_var', 'changed', 'data', 'failed', 'invocation', and 'item'.
    - name: Get the changed status from the dp_result variable
      ansible.builtin.set_fact:
        create_user_flag: "{{ item['changed'] }}"
      loop: "{{ hostvars['localhost']['dp_result']['results'] }}"
      when: item['item']['name'] == inventory_hostname
      no_log: true

    - name: Import create_user role from digitalocean
      include_role:
        name: digitalocean
        tasks_from: create_user
      vars:
        - ansible_ssh_host_key_checking: false
      when: create_user_flag

- name: Additional Setup of Netmaker Droplet
  hosts: do_netmaker
  gather_facts: true
  vars_files:
    - vars/vault.yaml
    - vars/main.yaml
  roles:
    - name: geerlingguy.security
      become: true

  tasks:
    - name: Import main role from base
      include_role:
        name: base

    - name: Import setup dotfiles role from base
      include_role:
        name: base
        tasks_from: setup_dotfiles
      vars:
        dotbot_skip_ssh_authorized_file: true
