---
- name: Create Netmaker Droplet
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/vault.yaml
    - vars/main.yaml

  tasks:
    - name: Configure DigitalOcean Droplet
      include_role:
        name: digitalocean


# The plays below will only run when the hosts group do_netmaker
# is defined and there is at least one host in the group
- name: Initial Setup of Netmaker Droplet
  hosts: do_netmaker
  gather_facts: false
  vars_files:
    - vars/vault.yaml
    - vars/main.yaml

  tasks:
    # Get the changed status from the droplet creation play
    # The create_user_flag will either be 'true' or 'false'.
    # This is used to determine if the user needs to be created the first time.
    # If the status is not changed, the create_user play will not run.
    - name: Get the changed status from the droplet_result variable
      ansible.builtin.set_fact:
        create_user_flag: "{{ item['changed'] }}"
      loop: "{{ hostvars['localhost']['droplet_result']['results'] }}"
      when: item['item']['name'] == inventory_hostname
      no_log: true

    - name: Import create_user role from digitalocean
      include_role:
        name: digitalocean
        tasks_from: create_user

    - name: Import main role from base
      include_role:
        name: base

    - name: Import setup dotfiles role from base
      include_role:
        name: base
        tasks_from: setup_dotfiles
      vars:
        dotbot_skip_ssh_authorized_file: true
