---
- name: Create Netmaker Droplet
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/vault.yaml
    - vars/main.yaml

  tasks:
    - name: Configure DigitalOcean Droplet
      include_role:
        name: digitalocean
      loop: "{{ netmaker_droplet }}"

# This play will always run when the hosts group do_netmaker is defined and
# there is at least one host in the group
- name: Setup Netmaker Droplet
  hosts: do_netmaker
  gather_facts: false
  vars_files:
    - vars/vault.yaml
    - vars/main.yaml
  vars:
    - ansible_ssh_host_key_checking: false

  tasks:
    - name: Import create_user role from digitalocean
      include_role:
        name: digitalocean
        tasks_from: create_user

    - name: Import main role from base
      include_role:
        name: base

    - name: Import setup dotfiles role from base
      include_role:
        name: base
        tasks_from: setup_dotfiles
      vars:
        dotbot_skip_ssh_authorized_file: true
