---
collections:
  - name: community.general
  - name: community.docker
  - name: community.digitalocean
  - name: ansible.posix
  - name: community.aws
  - name: amazon.aws

roles:
  - name: geerlingguy.security
