---
# complete site configuration.


# configure the DigitalOcean configuration
- name: Configure DigitalOcean
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Configure tags on digitalocean
      ansible.builtin.include_role:
        name: digitalocean
        tasks_from: tag

    - name: Configure firewalls on digitalocean
      ansible.builtin.include_role:
        name: digitalocean
        tasks_from: firewall

# run the netmaker playbook to configure a netmaker VPS
- name: Run the netmaker playbook
  ansible.builtin.import_playbook: services/netmaker/netmaker.yaml
