---
# complete site configuration.


# configure the DigitalOcean configuration
- name: Configure DigitalOcean
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Configure tags on digitalocean
    include_role:
      name: digitalocean
      tasks_from: tag

  - name: Configure firewalls on digitalocean
    include_role:
      name: digitalocean
      tasks_from: firewall

# run the netmaker playbook to configure a netmaker VPS
- import_playbook: netmaker.yaml
