---
# complete site configuration.


# configure the DigitalOcean configuration
- name: Configure DigitalOcean
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault/vault.yaml

  tasks:
    - name: Configure tags on digitalocean
      ansible.builtin.include_role:
        name: digitalocean
        tasks_from: tag
      tags:
        - digitalocean
        - digitalocean.tags

    - name: Configure firewalls on digitalocean
      ansible.builtin.include_role:
        name: digitalocean
        tasks_from: firewall
      tags:
        - digitalocean
        - digitalocean.firewall

# run the netmaker playbook to configure a netmaker VPS
- name: Run the netmaker playbook
  ansible.builtin.import_playbook: services/netmaker/netmaker.yaml
  tags:
    - netmaker

# run the netmaker_config playbook to configure netmaker
- name: Run the netmaker_config playbook
  ansible.builtin.import_playbook: services/netmaker/netmaker_config.yaml
  tags:
    - netmaker

# run the netclients playbook to configure netclients
- name: Run the netclients playbook
  ansible.builtin.import_playbook: services/netmaker/netclients.yaml
  tags:
    - netmaker
    - netmaker.netclient
