---
# Handlers for Netmaker

# Restart the Netmaker service using docker compose
- name: Restart Netmaker
  community.docker.docker_compose_v2:
    project_src: "{{ netmaker_directory }}"
    state: present
    restarted: true
    remove_orphans: true
  become: true

# Restart the Netclient service using docker compose
- name: Restart Netclient docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ netclient_directory }}"
    state: present
    restarted: true
  become: true

# Restart the Netclient service using systemd
- name: Restart Netclient systemd
  ansible.builtin.service:
    name: netclient
    state: restarted
    daemon_reload: true
  become: true
