---
# Host variables for docker-testing.home.stechsolutions.ca host

# other variables are set in group_vars/proxmox_nodes.yaml and
# proxmox_vms/hosts.yaml

fileserver_setup: true
fileserver_setup_nfs_client: true

fileserver_nfs_mounts:
  - path: /mnt/nfs/movies
    server: fileserver-testing.home.stechsolutions.ca
    nfs_export: /mnt/storage/movies
    options: defaults
    state: mounted
  - path: /mnt/nfs/tv
    server: fileserver-testing.home.stechsolutions.ca
    nfs_export: /mnt/storage/tv
    options: defaults
    state: mounted
