---
# Host variables for docker-testing.home.stechsolutions.ca host

# other variables are set in group_vars/proxmox_nodes.yaml and
# proxmox_vms/hosts.yaml

fileserver_setup: true
fileserver_setup_nfs_client: true
fileserver_setup_attached_disks: true

fileserver_attached_disks:
  # 10 GB test disk for docker compose
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
    partition_label: 10-GB-VD-0
    mount_point: "/home/{{ default_user }}/docker_mounts/proxy"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted

fileserver_nfs_mounts:
  - path: /mnt/nfs/movies
    server: storage.home.stechsolutions.ca
    nfs_export: /mnt/storage/movies
    options: defaults
    state: mounted
  - path: /mnt/nfs/tv
    server: storage.home.stechsolutions.ca
    nfs_export: /mnt/storage/tv
    options: defaults
    state: mounted
