---
# Host variables for fileserver-testing.home.stechsolutions.ca

# other variables are set in group_vars/proxmox_nodes.yaml

fileserver_setup: true
fileserver_install_nfs_server: true
fileserver_setup_mergerfs: true

fileserver_nfs_exports:
  - path: "/home/nfs/movies"
    machines:
      - name: 10.10.5.25  # docker-testing
        options: rw,sync,no_subtree_check,no_root_squash
  - path: "/home/nfs/tv"
    machines:
      - name: 10.10.5.25  # docker-testing
        options: rw,sync,no_subtree_check,no_root_squash

fileserver_mergerfs_disks:
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi3
    partition_label: 10-GB-VD-0
    mount_point: /mnt/disks/disk1
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted
    disk_type: data
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi4
    partition_label: 10-GB-VD-1
    mount_point: /mnt/disks/disk2
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted
    disk_type: data
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi5
    partition_label: 12-GB-VD-0
    mount_point: /mnt/disks/parity1
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted
    disk_type: parity

fileserver_mergerfs:
  src: /mnt/disks/disk*
  mount_point: /mnt/storage
  filesystem_type: fuse.mergerfs
  # yamllint disable rule:line-length
  options: "defaults,use_ino,allow_other,dropcacheonclose=true,category.create=mfs,minfreespace=25G,fsname=mergerfs"
  # yamllint enable rule:line-length
  state: mounted
