---
# Host variables for fileserver-testing.home.stechsolutions.ca

# other variables are set in group_vars/proxmox_nodes.yaml and
# proxmox_vms/hosts.yaml

fileserver_setup: true
fileserver_setup_mergerfs: true
fileserver_setup_snapraid: true
fileserver_install_nfs_server: true


fileserver_mergerfs_disks:
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi3
    partition_label: 10-GB-VD-0
    mount_point: /mnt/disks/disk1
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted
    disk_type: data
    snapraid_label: d1
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi4
    partition_label: 10-GB-VD-1
    mount_point: /mnt/disks/disk2
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted
    disk_type: data
    snapraid_label: d2
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi5
    partition_label: 12-GB-VD-0
    mount_point: /mnt/disks/parity1
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted
    disk_type: parity
    snapraid_label: parity

fileserver_mergerfs:
  src: /mnt/disks/disk*
  mount_point: /mnt/storage
  filesystem_type: fuse.mergerfs
  # yamllint disable rule:line-length
  options: "defaults,use_ino,allow_other,dropcacheonclose=true,category.create=mfs,minfreespace=25G,fsname=mergerfs"
  state: mounted
  mergerfs_tools:
    - name: mergerfs.ctl
      url: https://raw.githubusercontent.com/trapexit/mergerfs-tools/master/src/mergerfs.ctl
    - name: mergerfs.fsck
      url: https://raw.githubusercontent.com/trapexit/mergerfs-tools/master/src/mergerfs.fsck
    - name: mergerfs.dup
      url: https://raw.githubusercontent.com/trapexit/mergerfs-tools/master/src/mergerfs.dup
    - name: mergerfs.dedup
      url: https://raw.githubusercontent.com/trapexit/mergerfs-tools/master/src/mergerfs.dedup
    - name: mergerfs.balance
      url: https://raw.githubusercontent.com/trapexit/mergerfs-tools/master/src/mergerfs.balance
    - name: mergerfs.consolidate
      url: https://raw.githubusercontent.com/trapexit/mergerfs-tools/master/src/mergerfs.consolidate

fileserver_snapraid:
  url: https://github.com/amadvance/snapraid/releases/download/v12.3/snapraid-12.3.tar.gz
  # yamllint enable rule:line-length
  version: 12.3

fileserver_nfs_exports:
  - path: "/home/nfs/movies"
    machines:
      - name: 10.10.5.25  # docker-testing
        options: rw,sync,no_subtree_check,no_root_squash
  - path: "/home/nfs/tv"
    machines:
      - name: 10.10.5.25  # docker-testing
        options: rw,sync,no_subtree_check,no_root_squash
