---
# Defaults file for docker role.

# Only install docker if explicitly set to true
docker_install: false
docker_config: false

docker_data_dir: /home/{{ default_user }}/docker

docker_compose_dir: /home/{{ default_user }}/docker_compose

docker_daemon_options:
  data-root: '{{ docker_data_dir }}'
  log-opts:
    max-size: "10m"
