---
# Playbook to configure Netmaker client on nodes that require
# a manual install of the netclient. (i.e. remote nodest)

- name: Configure netclient for the 'netclients_manual' group
  hosts: localhost
  vars_files:
    - vars/netmaker.yaml
  tags:
    - netmaker.netclient

  tasks:
    - name: Get the enrollment keys from Netmaker
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: nmctl_enrollment
      vars:
        netmaker_create_enrollment_keys: false
      tags:
        - netmaker.netclient

    - name: Configure netclient_manual on the Netmaker server
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: nmctl_host_update
      vars:
        netmaker_host_name: "{{ hostvars[item]['netmaker_shorthost'] }}"
        # yamllint disable-line rule:line-length
        netmaker_host_definition: "{{ hostvars[item]['netmaker_host_settings'] }}"  # noqa: yaml[line-length]
      loop: "{{ groups['netclients_manual'] }}"
      tags:
        - netmaker
        - netmaker.netclient
        - netmaker.netclient.join
