---
# Playbook to install Netmaker client on nodes

- name: Get the enrollment keys from the Netmaker server
  hosts: localhost
  vars_files:
    - vars/netmaker.yaml
    - vars/networks.yaml
  tags:
    - netmaker.netclient

  tasks:
    - name: Get the enrollment keys from Netmaker
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: nmctl_enrollment_get
      tags:
        - netmaker.netclient
        - netmaker.netclient.systemd

- name: Install Netclient on nodes
  hosts: netclients
  vars_files:
    - ../../vault/vault.yaml
    - vars/netmaker.yaml
  tags:
    - netmaker.netclient

  tasks:

    - name: Install netclient systemd on nodes
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: netclient_install_systemd
      vars:
        # this is the list of enrollment keys from the Netmaker server
        # that is collected in the previous play
        # yamllint disable-line rule:line-length
        netmaker_enrollment_key_list: "{{ hostvars['localhost']['netmaker_enrollment_key_list'] }}"
        # yamllint disable-line rule:line-length
        netmaker_netclient_networks: "{{ hostvars[inventory_hostname]['netmaker_networks'] }}"
        # yamllint disable-line rule:line-length
        netmaker_host_name: "{{ hostvars[inventory_hostname]['netmaker_shorthost'] }}"
      tags:
        - netmaker.netclient
        - netmaker.netclient.systemd

- name: Configure netclient for the 'netclients' group
  hosts: localhost
  vars_files:
    - vars/netmaker.yaml
  tags:
    - netmaker.netclient

  tasks:
    # This sets all the options for the netclients on the Netmaker server
    - name: Configure netclient on the Netmaker server
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: nmctl_host_update
      vars:
        netmaker_host_name: "{{ hostvars[item]['netmaker_shorthost'] }}"
        # yamllint disable-line rule:line-length
        netmaker_host_definition: "{{ hostvars[item]['netmaker_host_settings'] }}"
      loop: "{{ groups['netclients'] }}"
      tags:
        - netmaker
        - netmaker.netclient
        - netmaker.netclient.join
