---
# Install the nmctl cli tool on the localhost.
#
# Then install the nmctl cli tool on the Netmaker server.
# Then configure the networks on the Netmaker server.
# Install and configure netclient on the Netmaker server.

- name: Configure NMCTL on the localhost
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../../vars/vault.yaml
    - ../../vars/main.yaml
    - ../../vars/netmaker.yaml

  tasks:
    - name: Install the nmctl tool
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: nmctl
      vars:
        netmaker_check_for_admin: false

- name: Configure Netmaker on the server
  hosts: do_netmaker
  gather_facts: false
  vars_files:
    - ../../vars/vault.yaml
    - ../../vars/main.yaml
    - ../../vars/netmaker.yaml

  tasks:
    - name: Install the nmctl tool
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: nmctl
      vars:
        netmaker_check_for_admin: true

    - name: Configure networks on Netmaker
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: nmctl_network

    - name: Configure enrollment keys on Netmaker
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: nmctl_enrollment

    # This adds the first network in the list to the Netclient
    - name: Install the netclient tool on the Netmaker server
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: netclient_install_docker
      vars:
        netmaker_network: "{{ netmaker_networks[0] }}"
        netmaker_nc_hostname: "{{ netmaker_droplet.name }}"

    # This adds the rest of the networks in the list to the Netclient
    # And sets all the options for the host and each node/network
    - name: Configure netclient on the Netmaker server
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: netclient_join_network
      vars:
        host_name: "{{ netmaker_droplet.name }}"
        networks: "{{ netmaker_networks[1:] }}"
        host_definition: "{{ netmaker_host_definition }}"

    # Add the external clients to the Netmaker server
    - name: Add external clients to the Netmaker server
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: nmctl_ext_client
      vars:
        external_clients: "{{ netmaker_ext_clients }}"
