---
# Install the nmctl cli tool on the localhost.
#
# Then install the nmctl cli tool on the Netmaker server.
# Then configure the networks on the Netmaker server.
# Install and configure netclient on the Netmaker server.

- name: Configure NMCTL on the localhost
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../../vault/vault.yaml
    - vars/netmaker.yaml
  vars:
    # This is needed as the role is installed on the localhost
    ansible_become_password: "{{ secret_become_pass }}"

  tasks:
    - name: Install the nmctl tool
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: nmctl
      tags:
        - netmaker
        - netmaker.full_setup
        - netmaker.nmctl

- name: Configure Netmaker on the server
  hosts: do_netmaker
  gather_facts: false
  vars_files:
    - ../../vault/vault.yaml
    - vars/netmaker.yaml
    - vars/ext_clients.yaml
    - vars/networks.yaml
  tags:
    - netmaker.full_setup

  tasks:
    - name: Install the nmctl tool
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: nmctl
      tags:
        - netmaker
        - netmaker.nmctl

    - name: Check for Netmaker admin user
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: nmctl_admin_create
      tags:
        - netmaker
        - netmaker.nmctl

    - name: Configure networks on Netmaker
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: nmctl_network
      tags:
        - netmaker
        - netmaker.network

    - name: Configure enrollment keys on Netmaker
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: nmctl_enrollment_create
      tags:
        - netmaker
        - netmaker.enrollment
        - netmaker.netclient
        - netmaker.netclient.docker

    # This play needs the netmaker_enrollment_key_list variable
    # to be set.  It is set in the nmctl_enrollment_create role above.
    - name: Install netclient systemd on Netmaker server
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: netclient_install_systemd
      vars:
        netmaker_netclient_networks: "{{ netmaker_networks }}"
        netmaker_host_name: "{{ netmaker_droplet.name }}"
      tags:
        - netmaker
        - netmaker.netclient
        - netmaker.netclient.systemd

    # This sets all the options for the host and each node/network
    - name: Configure netclient on the Netmaker server
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: nmctl_host_update
      vars:
        netmaker_host_name: "{{ netmaker_droplet.name }}"
        netmaker_host_definition: "{{ netmaker_server_host_settings }}"
      tags:
        - netmaker
        - netmaker.netclient
        - netmaker.netclient.join

    # Add the external clients to the Netmaker server
    - name: Add external clients to the Netmaker server
      ansible.builtin.include_role:
        name: netmaker
        tasks_from: nmctl_ext_client
      vars:
        netmaker_ext_clients_list: "{{ ext_clients }}"
      tags:
        - netmaker
        - netmaker.ext_client
