---
# Install the nmctl cli tool on the localhost.
#
# Then install the nmctl cli tool on the Netmaker server.
# Then configure the networks on the Netmaker server.
# Install and configure netclient on the Netmaker server.

- name: Configure Netmaker on the localhost
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../../vars/vault.yaml
    - ../../vars/main.yaml
    - ../../vars/netmaker.yaml

  tasks:
    - name: Install the nmctl tool
      ansible.builtin.import_tasks: ./tasks/nmctl.yaml


- name: Configure Netmaker on the server
  hosts: do_netmaker
  gather_facts: false
  vars_files:
    - ../../vars/vault.yaml
    - ../../vars/main.yaml
    - ../../vars/netmaker.yaml

  tasks:
    - name: Install the nmctl tool
      ansible.builtin.import_tasks: ./tasks/nmctl.yaml

    - name: Configure networks on Netmaker
      ansible.builtin.import_tasks: ./tasks/nmctl_network.yaml

    - name: Configure enrollment keys on Netmaker
      ansible.builtin.import_tasks: ./tasks/nmctl_enrollment.yaml

    - name: Install the netclient tool on the Netmaker server
      ansible.builtin.import_tasks: ./tasks/netclient.yaml
      vars:
        nm_token: "{{ nm_enrollment_key_list.stdout
                      | from_json
                      | selectattr('tags', 'contains', 'all-networks')
                      | map(attribute='token')
                      | first }}"

  handlers:
    - name: Import netmaker handlers
      ansible.builtin.import_tasks: handlers/main.yaml
