---
# Download cloud images

# block for download cloud images tasks
- name: Block for download cloud images tasks
  tags:
    - proxmox
    - proxmox.cloud_images
  block:
    # Create the ISO directory if it does not exist
    - name: Create the ISO directory if it does not exist
      ansible.builtin.file:
        path: "{{ proxmox_iso_path }}"
        state: directory
        mode: '0755'
      become: true

    # Remove the cloud images if state is absent or recreate
    - name: Remove the cloud images if state is absent or recreate
      ansible.builtin.file:
        path: "{{ proxmox_iso_path }}/{{ item.template_name }}.iso"
        state: absent
      loop: "{{ proxmox_cloud_imgs }}"
      become: true
      when: item.state in ["absent", "recreate"] and
            inventory_hostname in item.proxmox_nodes

    # Download the cloud images
    - name: Download the cloud images
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ proxmox_iso_path }}/{{ item.template_name }}.iso"
        mode: '0644'
        timeout: 60
      loop: "{{ proxmox_cloud_imgs }}"
      become: true
      when: item.state in ["present", "recreate"] and
            inventory_hostname in item.proxmox_nodes
