---
# Configure the requried repositories for Proxmox VE
# Remove the 'no subscription' message
#
# Credit: https://github.com/ironicbadger/ansible-role-proxmox-nag-removal

# Block for proxmox node repo tasks
- name: Block for proxmox node repo tasks
  tags:
    - proxmox
    - proxmox.node
  block:
    # Need to remove the enterprise repo file first
    - name: Ensure enterprise repo file is not present
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/pve-enterprise.list
        - /etc/apt/sources.list.d/ceph.list
        - /etc/apt/sources.list.d/pbs-enterprise.list

    - name: Add No Subscription Repository
      ansible.builtin.apt_repository:
        # yamllint disable-line rule:line-length
        repo: deb http://download.proxmox.com/debian/{{ item }} {{ ansible_distribution_release }} {{ item }}-no-subscription
        filename: "{{ item }}-no-subscription"
        update_cache: false
        state: present
      loop:
        - pbs
        - pve

    # credit: https://johnscs.com/remove-proxmox51-subscription-notice/
    # credit https://github.com/foundObjects/pve-nag-buster
    - name: Modify line in file to remove nag message
      ansible.builtin.replace:
        path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        regexp: 'res[\s\n]*\.data\.status\.toLowerCase\(\) !== .active.'
        replace: "false"
        backup: true
      become: true
      notify: Restart PVE or PBS proxy service
