---
# handlers file for base

# Restart postfix
- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
  become: true

# Systemctl reset-failed
- name: Systemctl reset-failed
  ansible.builtin.command: systemctl reset-failed
  changed_when: true
  become: true

# handler to apply the netplan configuration
- name: Apply netplan configuration
  ansible.builtin.command: netplan apply
  changed_when: true
  become: true

# Restart systemd-journald
- name: Restart systemd-journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
    daemon_reload: true
  changed_when: true
  become: true
