---
# handlers file for base

# Restart postfix
- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
  become: true

# Systemctl reset-failed
- name: Systemctl reset-failed
  ansible.builtin.command: systemctl reset-failed
  changed_when: true
  become: true
