---
# handlers file for base

# restart docker
- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true

# Restart postfix
- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
  become: true
