---
# vars file for digitalocean

# SSH Keys that are already added to the DigitalOcean account.
droplet_ssh_key_ids:
  - '32852449'  # Nelson's Thinkpad Laptop (DESKTOP-3PU4LF6)
  - '31285916'  # Nelson's Laptop Computer (DESKTOP-BSU9VDH)
  - '31285795'  # Nelsons Desktop Computer (DESKTOP-SJ8NAUC)
  - '26464123'  # Termius iOS App

# Tags that are already added to the DigitalOcean account.
droplet_tags:
  - "StechSolutions"
  - "SSH"
  - "Ansible"
