---
# vars file for digitalocean

# SSH Keys that are already added to the DigitalOcean account.
droplet_ssh_key_ids:
  - '32852449'  # Nelson's Thinkpad Laptop (DESKTOP-3PU4LF6)
  - '31285916'  # Nelson's Laptop Computer (DESKTOP-BSU9VDH)
  - '31285795'  # Nelsons Desktop Computer (DESKTOP-SJ8NAUC)
  - '26464123'  # Termius iOS App

# Tags that added to the DigitalOcean account.
digitalocean_tags:
  - name: "StechSolutions"
    state: "present"
  - name: "SSH"
    state: "present"
  - name: "Ansible"
    state: "present"
  # lowercase as it was orignally created as a lowercase and DigitalOcean
  # does not allow it to be recreated as uppercase.
  - name: "netmaker"
    state: "present"
  - name: "VPN"
    state: "present"
  - name: "HTTPS"
    state: "present"

# Tags that are added to all DigitalOcean Droplets managed by Ansible.
digitalocean_default_tags:
  - "StechSolutions"
  - "SSH"
  - "Ansible"

digitalocean_firewall:
  - name: "StechSolutions-Base"
    state: "present"
    tags: ["StechSolutions"]
    outbound_rules:
      - ports: "1-65535"
        protocol: "icmp"
        destinations:
          addresses: ["0.0.0.0/0", "::/0"]
      - ports: "1-65535"
        protocol: "tcp"
        destinations:
          addresses: ["0.0.0.0/0", "::/0"]
      - ports: "1-65535"
        protocol: "udp"
        destinations:
          addresses: ["0.0.0.0/0", "::/0"]
  - name: "StechSolutions-SSH"
    state: "present"
    tags: ["SSH"]
    inbound_rules:
      - ports: "22"
        protocol: "tcp"
        sources:
          addresses: ["0.0.0.0/0", "::/0"]
    outbound_rules:
      - ports: "22"
        protocol: "tcp"
        destinations:
          addresses: ["0.0.0.0/0", "::/0"]
  - name: "StechSolutions-VPN"
    state: "present"
    tags: ["VPN"]
    inbound_rules:
      - ports: "51820-51830"
        protocol: "udp"
        sources:
          addresses: ["0.0.0.0/0", "::/0"]
    outbound_rules:
      - ports: "51820-51830"
        protocol: "udp"
        destinations:
          addresses: ["0.0.0.0/0", "::/0"]
