---

# Ensure the required directories exist
- name: Ensure Sanoid directories exist
  ansible.builtin.file:
    path: /etc/sanoid
    state: directory
    mode: '0755'
  become: true

# create the config file from a template
- name: Create the Sanoid config file
  ansible.builtin.template:
    src: sanoid.conf.j2
    dest: /etc/sanoid/sanoid.conf
    mode: '0644'
  become: true
  when: sanoid_datasets is defined and sanoid_templates is defined
  tags:
    - sanoid

# Create the Sanoid healthcheck script
- name: Create the Sanoid healthcheck script
  ansible.builtin.template:
    src: sanoid_healthcheck.sh.j2
    dest: "{{ sanoid_healthcheck_script_path }}"
    mode: '0755'
  become: true
  when: sanoid_hc_url is defined and sanoid_hc_uuid is defined
  tags:
    - sanoid
