---
# This playbook will setup all the specified VMs. It will update the DNS
# entries in Pi-hole and then create the VMs in Proxmox.It will then start
# the VMs and wait for them to be ready. Once the VMs are ready, it will
# update the known_hosts file for the IP and hostname.

# Run the pihole playbook to make sure the DNS records are correct
- name: Run the pihole role
  ansible.builtin.import_playbook: "../../playbooks/pihole.yaml"
  tags:
    - pihole
    - proxmox
    - proxmox.vm
    - proxmox.vm.create
    - base.known_hosts

# Run the proxmox role
- name: Run the proxmox role
  hosts: proxmox_nodes
  vars_files:
    - ../../vault/vault.yaml
  tags:
    - proxmox
    - proxmox.vm
    - proxmox.vm.create

  tasks:
    # This creates the VMs
    - name: Run the proxmox role to create VMs
      ansible.builtin.include_role:
        name: proxmox
        tasks_from: create_vm
      vars:
        proxmox_template_id: "{{ hostvars[item].proxmox_vm.template_id }}"
        proxmox_vm: "{{ hostvars[item].proxmox_vm }}"
      loop: "{{ groups['proxmox_vms'] }}"

    # Start the VMs and wait for them to be ready
    - name: Run the proxmox role to start VMs
      ansible.builtin.include_role:
        name: proxmox
        tasks_from: start_vm
      vars:
        proxmox_vm: "{{ hostvars[item].proxmox_vm }}"
        proxmox_ip: "{{ hostvars[item].network.ip }}"
      loop: "{{ groups['proxmox_vms'] }}"
