---
# This playbook will configure the Proxmox host.

# Run the pihole playbook to make sure the DNS records are correct
- name: Run the pihole role
  ansible.builtin.import_playbook: "../../playbooks/pihole.yaml"
  tags:
    - pihole
    - proxmox
    - proxmox.pve
    - base.known_hosts

# Get the ntfy tokens to use later in the playbook for notifications.
- name: Get the ntfy tokens
  hosts: docker-cloud-01
  gather_facts: false
  vars_files:
    - ../../vault/vault.yaml
  tasks:
    - name: Get the ntfy tokens
      ansible.builtin.include_role:
        name: ntfy
        tasks_from: tokens.yaml

    # Make the ntfy_tokens_extracted variable available to the proxmox_nodes hosts
    - name: Make the ntfy_tokens_extracted variable available to the proxmox_nodes
      ansible.builtin.add_host:
        name: "{{ item }}"
        ntfy_tokens_extracted: "{{ ntfy_tokens_extracted }}"
      loop: "{{ groups['proxmox_nodes'] }}"
      delegate_to: localhost

# These first tasks are run as the root user since it includes
# setting up the new user with the ssh keys.
- name: Make sure the Proxmox host is setup
  hosts: proxmox_nodes
  vars_files:
    - ../../vault/vault.yaml
  vars:
    ansible_host_key_checking: false
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'
    ansible_user: root
    ansible_ssh_pass: "{{ secret_user_password }}"
  tags:
    - proxmox
    - proxmox.pve
    - base.known_hosts

  tasks:
    # Update the known_hosts var_file
    - name: Update the known_hosts var_file
      ansible.builtin.include_role:
        name: base
        tasks_from: update_known_hosts
      vars:
        base_hostname: "{{ item }}"
        base_state: present
        base_comment: "Proxmox Host: {{ ansible_hostname }}"
      loop:
        - "{{ ansible_default_ipv4.address }}"
        - "{{ ansible_hostname }}"
        - "{{ inventory_hostname }}"
      loop_control:
        label: "{{ item }}"
      tags:
        - base.known_hosts

    # Configure the Proxmox repos
    - name: Configure the Proxmox repos
      ansible.builtin.include_role:
        name: proxmox
        tasks_from: pve_repos

    # Run the base role
    # Add the ssh keys so we can login as the new user later
    - name: Run the base role
      ansible.builtin.include_role:
        name: base
      vars:
        base_user_add_ssh_keys: true
      tags:
        - base.apt
        - base.user
        - base.timezone

    # Update the proxmox permissions
    - name: Update the proxmox permissions
      ansible.builtin.include_role:
        name: proxmox
        tasks_from: pve_create_groups
      tags:
        - proxmox.pve.permissions

    # Update the proxmox users
    - name: Update the proxmox users
      ansible.builtin.include_role:
        name: proxmox
        tasks_from: pve_create_users
      tags:
        - proxmox.pve.users

    # Setup the Proxmox notifications
    - name: Setup the Proxmox notifications
      ansible.builtin.include_role:
        name: proxmox
        tasks_from: pve_notifications
      tags:
        - proxmox.pve.notifications

    # Update the proxmox storage
    - name: Update the proxmox storage
      ansible.builtin.include_role:
        name: proxmox
        tasks_from: pve_storage
      when: proxmox_storage is defined
      tags:
        - proxmox.pve.storage

    # Update the proxmox ACME certificates
    - name: Update the proxmox ACME certificates
      ansible.builtin.include_role:
        name: proxmox
        tasks_from: pve_acme
      tags:
        - proxmox.pve.acme

    # Update the proxmox backups healthchecks check
    - name: Update the proxmox backups healthchecks check
      ansible.builtin.include_role:
        name: proxmox
        tasks_from: pve_backup_healthchecks
      tags:
        - proxmox.pve.backup.healthchecks

    # Update the proxmox backups
    - name: Update the proxmox backups
      ansible.builtin.include_role:
        name: proxmox
        tasks_from: pve_create_backup
      tags:
        - proxmox.pve.backup

# These tasks can be run as the new user
- name: Continue setting up the Proxmox host as the new user
  hosts: proxmox_nodes
  vars_files:
    - ../../vault/vault.yaml
  tags:
    - proxmox
    - proxmox.pve
  tasks:

    # This is required to explicitly get the ansible facts for the
    # base.geerlingguy.security role if running only that role via tags.
    - name: Do ansible setup
      ansible.builtin.setup:
      tags:
        - never
        - base.geerlingguy.security

    # Run the base role
    - name: Run the base role
      ansible.builtin.include_role:
        name: base
      tags:
        - base.apt
        - base.docker
        - base.timezone
        - base.dotfiles

    # Run the geerlingguy.security role
    - name: Import geerlingguy.security role
      ansible.builtin.import_role:
        name: geerlingguy.security
      become: true
      tags:
        - base.geerlingguy.security

    # Run the NUT role
    - name: Run the NUT role
      ansible.builtin.include_role:
        name: nut
      when: proxmox_nut_configure
      tags:
        - nut
