---
# handlers file for docker role

# restart docker
- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  register: docker_restart_result
  become: true

# restart docker container
- name: Restart docker container
  community.docker.docker_container:
    name: "{{ container }}"
    state: started
    restart: true
  loop: "{{ docker_containers_to_restart }}"
  loop_control:
    loop_var: container
    label: "{{ container }}"
  become: true
  when: docker_containers_to_restart is defined and
        docker_restart_result is not defined
