---
# defaults file for base

# whether to update and upgrade apt packages or not
# can be "dist", "full", "no", "safe", "yes"
# if "no" is set, then just apt update is run
base_apt_upgrade_packages: "yes"

# whether to update apt packages or not
base_apt_update_packages: true

# variables for rebooting the host
base_reboot_host_if_required: true

# the base packages to install
base_packages:
  - git
  - jq
  - vnstat
  - wireguard
  - wireguard-tools

base_remove_packages:
  - neofetch

# the base services to enable and start
# eg format will include the service name, state, and optional enabled state
# base_services:
#   - name: "service_name"
#     state: "started"
#     enabled: true
#   - name: "service_name"
#     state: "stopped"
#     enabled: false
base_services: []

# the base settings for user setup
base_user_run_setup: true

base_user_default: "{{ default_user }}"
base_user_password_default: "{{ secret_user_password }}"
base_user_password_prehashed: "{{ secret_user_password_prehashed }}"

# whether to add ssh keys to the user or not
# defaults to false because generally the ssh keys
# are added using the dotfiles method.
base_user_add_ssh_keys: false
base_user_groups:
  - sudo

# variables for the dotfiles
base_dotfiles_dir: /home/{{ default_user }}/dotfiles
base_dotfiles_repo: https://github.com/nstoik/dotfiles

base_dotfiles:
  install: false
  dotbot_skip_ssh_authorized_file: false

# variables for docker
# whether to install docker or not
# the rest of the docker setup is specified in the docker role
base_docker_install: false

# variables for postfix
base_postfix:
  install: false
  relayhost: ""
  relayhost_username: ""
  relayhost_password: ""

# variables for timezone
base_timezone: "America/Edmonton"
