---
# defaults file for base

# the base packages to install
base_packages:
  - git
  - vnstat
  - wireguard
  - wireguard-tools

# the base services to enable and start
base_services: []

# variables for the dotfiles
base_dotfiles_dir: /home/{{ default_user }}/dotfiles
base_dotfiles_repo: https://github.com/nstoik/dotfiles

# variables for docker
base_docker_data_dir: /home/{{ default_user }}/docker

base_docker_daemon_options:
  data-root: '{{ base_docker_data_dir }}'
  log-opts:
    max-size: "10m"
