---
# defaults file for base

# the base packages to install
base_packages:
  - git
  - vnstat

# variables for the dotfiles
dotfiles_dir: /home/{{ default_user }}/dotfiles
dotfiles_repo: https://github.com/nstoik/dotfiles

dotbot_skip_ssh_authorized_file: false
