---
# defaults file for base

# the base packages to install
base_packages:
  - git
  - vnstat
  - wireguard

# variables for the dotfiles
dotfiles_dir: /home/{{ default_user }}/dotfiles
dotfiles_repo: https://github.com/nstoik/dotfiles

