---
# defaults file for base

# the base packages to install
base_packages:
  - git
  - vnstat
  - wireguard

# variables for the dotfiles
dotfiles_dir: /home/{{ default_user }}/dotfiles
dotfiles_repo: https://github.com/nstoik/dotfiles

# variables for docker
docker_data_dir: /home/{{ default_user }}/docker

docker_daemon_options:
  data-root: '{{ docker_data_dir }}'
  log-opts:
    max-size: "10m"
