---
- 3DPrinting:
    - OctoPrint:
        href: http://octoprint.home.stechsolutions.ca
        description: OctoPrint
        icon: octoprint.png
        widget:
          type: octoprint
          url: http://octoprint.home.stechsolutions.ca
          key: "{{ secret_octoprint_key }}"
          printer_state:
          temp_tool:
          temp_bed:
          job_completion:
- Network:
    - PiHole-1:
        href: http://pihole-1.home.stechsolutions.ca/admin
        description: PiHole-1
        icon: pi-hole.png
        widget:
          type: pihole
          url: http://pihole-1.home.stechsolutions.ca
          version: 5
          key: "{{ secret_pihole_password_hash }}"
          queries:
          blocked:
          gravity:
    - PiHole-2:
        href: http://pihole-2.home.stechsolutions.ca/admin
        description: PiHole-2
        icon: pi-hole.png
        widget:
          type: pihole
          url: http://pihole-2.home.stechsolutions.ca
          version: 5
          key: "{{ secret_pihole_password_hash }}"
          queries:
          blocked:
          gravity:
    - Unifi OS:
        href: https://unifi.home.stechsolutions.ca
        description: Unifi OS
        icon: unifi.png
    - Unifi Controller:
        href: https://unifi.home.stechsolutions.ca/network/default/dashboard
        description: Unifi Controller
        icon: unifi-controller.png
        widget:
          type: unifi
          url: https://unifi.home.stechsolutions.ca
          username: HomepageUser
          password: "{{  secret_unifi_username_password}}"
          uptime:
          wan:
          lan:
    - Unifi Protect:
        href: https://unifi.home.stechsolutions.ca/protect/dashboard
        description: Unifi Protect
        icon: unifi-protect.png
