---
# Host variables for docker-cloud-01 host.

# tailscale
tailscale_setup: true
tailscale_authkey: "{{ secret_ts_client_secret }}?ephemeral=false&preauthorized=true"
tailscale_args: |
  --advertise-tags='tag:server'
  --accept-routes
  --accept-dns

fileserver_setup: true
fileserver_setup_swap_file: true

fileserver_swap_file:
  path: /swapfile
  size: 2G

# docker container configuration files
docker_configuration_files:
  - name: traefik.yaml
    src: "{{ inventory_dir }}/../files/traefik/traefik-prod-no-file-provider.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/traefik/traefik.yaml
    mode: '0664'
    container_name: traefik

# docker container template files
docker_template_files:
  - name: server.yaml
    src: "{{ inventory_dir }}/../files/ntfy/server.yaml"
    dest: /home/{{ default_user }}/docker_mounts/monitoring/ntfy/server.yaml
    mode: '0664'
    container_name: ntfy

# docker mounts subfolders
docker_mounts_subfolders:
  - name: postgres_hc
    dest: /home/{{ default_user }}/docker_mounts/monitoring/postgres
    mode: '0775'
    container_name: postgres_hc_db
  - name: uptime-kuma
    dest: /home/{{ default_user }}/docker_mounts/monitoring/uptime-kuma
    mode: '0775'
    container_name: uptime-kuma

# docker compose:
docker_compose:
  - compose_name: proxy
    state: present
    networks:
      traefik:
        name: traefik
      docker-proxy:
        name: docker-proxy
    containers:
      - container_name: traefik
        image: traefik:v3.1
        networks:
          - traefik
          - docker-proxy
        healthcheck:
          test: ['CMD', 'traefik', 'healthcheck', '--ping']
          interval: 60s
          timeout: 10s
          retries: 3
          start_period: 40s
        environment:
          - TZ=America/Edmonton
          - "CF_API_EMAIL={{ default_user_email }}"
          - "CF_DNS_API_TOKEN={{ secret_cf_token }}"
        ports:
          - 80:80
          - 443:443
        depends_on:
          - docker-socket-proxy
        volumes:
          - "/home/{{ default_user }}/docker_mounts/proxy/traefik:/etc/traefik"
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          - "traefik.docker.network=traefik"
          - "traefik.http.routers.dashboard.rule=Host(`docker-cloud-01.stechsolutions.ca`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
          - "traefik.http.routers.dashboard.service=api@internal"
          - "traefik.http.routers.dashboard.middlewares=auth"
          - "traefik.http.middlewares.auth.basicauth.users={{ default_user }}:{{ secret_traefik_dashboard_password_hash }}"
          - "traefik.http.routers.dashboard.entrypoints=websecure"
          - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
          - "homepage.group=Proxy"
          - "homepage.name=Traefik Remote"
          - "homepage.description=Remote Reverse Proxy"
          - "homepage.icon=traefik.png"
          - "homepage.href=https://docker-cloud-01.stechsolutions.ca/dashboard/#/"
          - "homepage.siteMonitor=https://docker-cloud-01.stechsolutions.ca/dashboard/#/"
          - "homepage.widget.type=traefik"
          - "homepage.widget.url=https://docker-cloud-01.stechsolutions.ca"
          - "homepage.widget.username={{ default_user }}"
          - "homepage.widget.password={{ secret_traefik_dashboard_password }}"
          - "homepage.widget.routers="
          - "homepage.widget.services="
          - "homepage.widget.middleware="
          - "wud.tag.include=^v?\\d+\\.\\d+\\.\\d+$"
          - "wud.link.template=https://github.com/traefik/traefik/releases"
      - container_name: docker-socket-proxy
        image: tecnativa/docker-socket-proxy:0.2.0
        networks:
          - docker-proxy
        healthcheck:
          test: wget --spider http://docker-socket-proxy:2375/version || exit 1
          interval: 60s
          timeout: 10s
          retries: 3
          start_period: 40s
        environment:
          - CONTAINERS=1 # Allow access to viewing containers
          - IMAGES=1 # Allow access to viewing images
          - POST=0 # Disallow any POST operations (effectively read-only)
        ports:
          # Only expose on the tailscale interface
          - 100.83.135.110:2375:2375
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        restart: unless-stopped
        labels:
          - "wud.tag.include=^v?\\d+\\.\\d+\\.\\d+$"
          - "wud.link.template=https://github.com/Tecnativa/docker-socket-proxy/releases"
  - compose_name: monitoring
    state: present
    networks:
      traefik:
        name: traefik
        external: true
      hc_postgres:
        name: hc_postgres
    containers:
      - container_name: ntfy
        image: binwiederhier/ntfy:v2.11.0
        command: "serve"
        networks:
          - traefik
        healthcheck:
          test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
          interval: 60s
          timeout: 10s
          retries: 3
          start_period: 40s
        volumes:
          - "/home/{{ default_user }}/docker_mounts/monitoring/ntfy:/var/lib/ntfy"
          - "/home/{{ default_user }}/docker_mounts/monitoring/ntfy/server.yaml:/etc/ntfy/server.yml"
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.ntfy.rule=Host(`ntfy.stechsolutions.ca`)"
          - "traefik.http.services.ntfy.loadbalancer.server.port=80"
          - "traefik.http.routers.ntfy.entrypoints=websecure"
          - "traefik.http.routers.ntfy.tls.certresolver=letsencrypt"
          - "homepage.group=Monitoring"
          - "homepage.name=Ntfy"
          - "homepage.description=Ntfy Messaging"
          - "homepage.icon=ntfy.png"
          - "homepage.href=https://ntfy.stechsolutions.ca"
          - "homepage.siteMonitor=https://ntfy.stechsolutions.ca"
          - "wud.tag.include=^v?\\d+\\.\\d+\\.\\d+$"
          - "wud.link.template=https://github.com/binwiederhier/ntfy/releases"
      - container_name: postgres_hc_db
        image: postgres:17.1
        user: 1000:1000
        networks:
          - hc_postgres
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U {{ hc_db_user }} -d {{ hc_db_name }}"]
          interval: 60s
          timeout: 10s
          retries: 3
          start_period: 40s
        environment:
          - POSTGRES_DB={{ hc_db_name }}
          - POSTGRES_USER={{ hc_db_user }}
          - POSTGRES_PASSWORD={{ secret_hc_db_password }}
        volumes:
          - "/home/{{ default_user }}/docker_mounts/monitoring/postgres:/var/lib/postgresql/data"
          - "/etc/passwd:/etc/passwd:ro"
        restart: unless-stopped
        labels:
          - "wud.tag.include=^v?\\d+\\.\\d+\\.\\d+$"
          - "wud.link.template=https://www.postgresql.org/docs/release/"
      - container_name: healthchecks
        image: healthchecks/healthchecks:v3.7
        networks:
          - traefik
          - hc_postgres
        environment:
          - ALLOWED_HOSTS={{ hc_allowed_hosts }}
          - DB={{ hc_db }}
          - DB_HOST={{ hc_db_host }}
          - DB_NAME={{ hc_db_name }}
          - DB_USER={{ hc_db_user }}
          - DB_PASSWORD={{ secret_hc_db_password }}
          - DB_PORT={{ hc_db_port }}
          - DEBUG={{ hc_debug }}
          - DEFAULT_FROM_EMAIL={{ hc_default_from_email }}
          - EMAIL_HOST={{ hc_email_host }}
          - EMAIL_HOST_PASSWORD={{ hc_email_host_password }}
          - EMAIL_HOST_USER={{ hc_email_host_user }}
          - EMAIL_PORT={{ hc_email_port }}
          - REGISTRATION_OPEN={{ hc_registration_open }}
          - SECRET_KEY={{ hc_secret_key }}
          - SITE_NAME={{ hc_site_name }}
          - SITE_LOGO_URL={{ hc_site_logo_url }}
          - SITE_ROOT={{ hc_site_root }}
          # Reduce the number of worker processes to 1
          - UWSGI_PROCESSES=1
        depends_on:
          - postgres_hc_db
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.hc.rule=Host(`{{ hc_allowed_hosts }}`)"
          - "traefik.docker.network=traefik"
          - "traefik.http.services.hc.loadbalancer.server.port=8000"
          - "traefik.http.routers.hc.entrypoints=websecure"
          - "traefik.http.routers.hc.tls.certresolver=letsencrypt"
          - "homepage.group=Monitoring"
          - "homepage.name=Healthchecks"
          - "homepage.description=Self-hosted Healthchecks"
          - "homepage.icon=healthchecks-v2.png"
          - "homepage.href=https://hc.stechsolutions.ca"
          - "homepage.siteMonitor=https://hc.stechsolutions.ca"
          - "homepage.widget.type=healthchecks"
          - "homepage.widget.url=https://hc.stechsolutions.ca"
          - "homepage.widget.key={{ secret_hc_projects['Stechsolutions'].api_key }}"
          - "wud.tag.include=^v?\\d+\\.\\d+\\.\\d+$"
          - "wud.link.template=https://github.com/healthchecks/healthchecks/releases"
      - container_name: uptime-kuma
        image: louislam/uptime-kuma:2.0.0-beta.0
        networks:
          - traefik
        environment:
          - PUID=1000
          - PGID=1000
        volumes:
          - "/home/{{ default_user }}/docker_mounts/monitoring/uptime-kuma:/app/data"
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.uptime-kuma.rule=Host(`uptime.stechsolutions.ca`)"
          - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
          - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
          - "traefik.http.routers.uptime-kuma.tls.certresolver=letsencrypt"
          - "homepage.group=Monitoring"
          - "homepage.name=Uptime Kuma"
          - "homepage.description=Uptime Monitoring"
          - "homepage.icon=uptime-kuma.png"
          - "homepage.href=https://uptime.stechsolutions.ca"
          - "homepage.siteMonitor=https://uptime.stechsolutions.ca"
          - "homepage.widget.type=uptimekuma"
          - "homepage.widget.url=https://uptime.stechsolutions.ca"
          - "homepage.widget.slug=all-services"
          - "wud.tag.include=^v?\\d+\\.\\d+\\.\\d+$"
          - "wud.link.template=https://github.com/louislam/uptime-kuma/releases"
