---
# ntfy configuration for docker-cloud-01

# ntfy variables
ntfy_setup: true
# these two are set in group_vars/all.yaml
# ntfy_user: "{{ default_user }}"
# ntfy_base_url: "https://ntfy.stechsolutions.ca"
ntfy_password: "{{ secret_ntfy_password }}"

ntfy_tokens:
  - label: Healthchecks
  - label: Proxmox
  - label: Test
