---
# Handlers for Netmaker

# Restart the Netmaker service using docker-compose
- name: Restart Netmaker
  community.docker.docker_compose:
    project_src: "{{ netmaker_directory }}"
    state: present
    restarted: true
  become: true
