---
# Install Tailscale on Ubuntu

- name: Add Tailscale signing key
  ansible.builtin.get_url:
    url: "{{ tailscale_apt_signkey }}"
    dest: "{{ tailscale_apt_keyring_path }}"
    mode: "0644"
  become: true

- name: Add Tailscale repo to apt sources
  ansible.builtin.apt_repository:
    repo: "{{ tailscale_apt_repository }}"
    # the tailscale updater fails unless filename is "tailscale.list"
    filename: tailscale
    state: present
  become: true

- name: Install Tailscale
  ansible.builtin.apt:
    name: "{{ tailscale_package }}"
    state: present
  become: true

- name: Enable and start Tailscale service
  ansible.builtin.systemd:
    name: "{{ tailscale_service }}"
    state: started
    enabled: true
  become: true

- name: Wait for Tailscale to be ready
  ansible.builtin.wait_for:
    path: "{{ tailscale_socket }}"
    state: present
    timeout: 60
