---
# Setup IP forwarding on a Linux host

- name: Add IP forwarding configuration for Tailscale
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-tailscale.conf
    content: |
      # Enable IP forwarding for Tailscale
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Reload sysctl
