---

# install tailscale
- name: Install Tailscale
  ansible.builtin.include_tasks:
    file: install.yaml
  tags:
    - tailscale
    - tailscale.install

- name: Bring Tailscale up
  ansible.builtin.command: >
    tailscale up --authkey="{{ tailscale_authkey }}" {{ tailscale_args | default('') }}
  changed_when: false
  become: true
  tags:
    - tailscale
    - tailscale.up
