---
# tasks file for digitalocean

# Configure a DigitalOcean Droplet
- name: Set Droplet State
  community.digitalocean.digital_ocean_droplet:
    oauth_token: "{{ secret_do_token }}"
    state: "{{ droplet.state | default('present') }}"
    name: "{{ droplet.name }}"
    size: "{{ droplet.size | default(droplet_size) }}"
    region: "{{ droplet_region }}"
    image: "{{ droplet_image }}"
    ssh_keys: "{{ droplet_ssh_key_ids }}"
    tags: "{{ digitalocean_default_tags + droplet.tags | default([]) }}"
    monitoring: true
    project_name: "nelsonstoik"
    unique_name: true
  register: droplet_result


- name: Refresh inventory
  ansible.builtin.meta: refresh_inventory
