---
# tasks file for digitalocean

# Configure a DigitalOcean Droplet
- name: Set Droplet State
  community.digitalocean.digital_ocean_droplet:
    oauth_token: "{{ secret_do_token }}"
    state: "{{ droplet.state | default('present') }}"
    name: "{{ droplet.name }}"
    size: "{{ droplet.size | default(droplet_size) }}"
    region: "{{ droplet_region }}"
    image: "{{ droplet_image }}"
    ssh_keys: "{{ droplet_ssh_key_ids }}"
    tags: "{{ digitalocean_default_tags + droplet.tags | default([]) }}"
    monitoring: true
    project_name: "nelsonstoik"
    unique_name: true
  register: digitalocean_droplet_result

# attach a block storage volume to a droplet if the volume is defined
- name: Attach DigitalOcean block storage
  community.digitalocean.digital_ocean_block_storage:
    oauth_token: "{{ secret_do_token }}"
    state: "{{ droplet['volume']['state'] }}"
    command: "attach"
    region: "{{ droplet_region }}"
    volume_name: "{{ droplet['volume']['volume_name'] }}"
    droplet_id: "{{ digitalocean_droplet_result.data.droplet.id }}"
  when: droplet['volume'] is defined and droplet.state == 'present'

- name: Refresh inventory
  ansible.builtin.meta: refresh_inventory
