---
# tasks for digitalocean tag configuration

- name: Set DigitalOcean tags
  community.digitalocean.digital_ocean_tag:
    oauth_token: "{{ secret_do_token }}"
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ digitalocean_tags }}"
