---
# Provision a Raspberry Pi
#
# Required inputs:
#  rpi_ip: The IP address of the Raspberry Pi

# Wait for the Raspberry Pi to be ready
- name: Wait for the Raspberry Pi to be ready
  block:
    - name: Wait for the Raspberry Pi to be ready
      ansible.builtin.wait_for:
        host: "{{ rpi_ip }}"
        port: 22
        delay: 10
        timeout: 300
      changed_when: false

    - name: Wait for cloud-init to finish
      ansible.builtin.wait_for:
        host: "{{ rpi_ip }}"
        path: /var/lib/cloud/instance/boot-finished
        delay: 10
        timeout: 600
      changed_when: false
