---
# group_vars for the all group (client_welca inventory)
ansible_become_password: "{{ secret_become_pass }}"

# Default user values
default_user: "welca"
default_user_email: "nstoik@stechsolutions.ca"
# secret_user_password is set in vaults/client_welca/vault.yaml

# timezone
base_timezone: "America/Edmonton"

base_controller_user: "nelson"
known_hosts_ansible_file: "/home/{{ base_controller_user }}/.ssh/known_hosts_ansible"

