---
global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "tcp://docker-socket-proxy:2375"
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"

log:
  level: INFO

certificatesResolvers:
  letsencrypt:
    acme:
      storage: "/etc/traefik/acme.json"
      dnsChallenge:
        provider: cloudflare
