---
global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

accessLog:
  filepath: /etc/traefik/access.log
  format: json
  fields:
    defaultMode: keep
    names:
      StartUTC: drop

ping: {}

api:
  dashboard: true
  insecure: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

providers:
  docker:
    endpoint: "tcp://docker-socket-proxy:2375"
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"

log:
  level: DEBUG

certificatesResolvers:
  letsencrypt:
    acme:
      storage: "/etc/traefik/acme.json"
      # staging server for letsencrypt
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
