---
global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  metrics:
    address: ":8081"

accessLog:
  filepath: /etc/traefik/access.log
  format: json
  fields:
    defaultMode: keep
    names:
      StartUTC: drop

ping: {}

api:
  dashboard: true

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

providers:
  docker:
    endpoint: "tcp://docker-socket-proxy:2375"
    exposedByDefault: false

log:
  level: INFO

certificatesResolvers:
  letsencrypt:
    acme:
      storage: "/etc/traefik/acme.json"
      dnsChallenge:
        provider: cloudflare
