# traefik.yaml

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

log:
  level: INFO

certificatesResolvers:
  letsencrypt:
    acme:
      storage: "/etc/traefik/acme.json"
      dnsChallenge:
        provider: cloudflare
