---
# tailscale variables for pi-speedtest.home.stechsolutions.ca host

# tailscale
tailscale_setup: true
tailscale_authkey: "{{ secret_ts_client_secret_v2 }}?ephemeral=false&preauthorized=true"
tailscale_args: |
  --advertise-tags='tag:server,tag:docker-monitoring'
  --accept-routes
  --accept-dns
