---
# main tasks file for the fileserver role
#
# inputs:
#   - fileserver_setup_mergerfs: boolean
#   - fileserver_setup_nfs_server: boolean
#   - fileserver_setup_nfs_client: boolean
#   - fileserver_setup_snapraid: boolean
#   - fileserver_setup_zfs: boolean
#   - fileserver_setup_attached_disks: boolean
#   - fileserver_setup_swap_file: boolean

# Setup attached disks with ext4 filesystem
# These are typically the virtual disks attached to the VM
- name: Setup attached disks with ext4 filesystem
  ansible.builtin.include_tasks: setup_disks.yaml
  tags:
    - fileserver
    - fileserver.ext4
  when: fileserver_setup_attached_disks is true

# Setup swap file
- name: Setup swap file
  ansible.builtin.include_tasks: setup_swap_file.yaml
  tags:
    - fileserver
    - fileserver.swap
  when: fileserver_setup_swap_file is true

# Setup mergerfs
# This would typically be real disks passed through to the VM
- name: Block for mergerfs tasks
  tags:
    - fileserver
    - fileserver.mergerfs
    - fileserver.ext4
  when: fileserver_setup_mergerfs is true
  block:
    # Setup required disks with ext4 filesystem
    - name: Setup required disks with ext4 filesystem
      ansible.builtin.include_tasks: setup_ext4.yaml
      vars:
        fileserver_ext4_disks: "{{ fileserver_mergerfs_disks }}"

    # Setup mergerfs
    - name: Setup mergerfs
      ansible.builtin.include_tasks: setup_mergerfs.yaml

# Setup SnapRAID and SnapRAID aio
- name: Setup SnapRAID and SnapRAID aio
  tags:
    - fileserver
    - fileserver.snapraid
  when: fileserver_setup_snapraid is true
  block:
    # Setup SnapRAID
    - name: Setup SnapRAID
      ansible.builtin.include_tasks: setup_snapraid.yaml

    # Setup SnapRAID aio
    - name: Setup SnapRAID aio
      ansible.builtin.include_tasks: setup_snapraid_aio.yaml

# Setup ZFS
# This would typically be real disks passed through to the VM
- name: Setup ZFS pool
  tags:
    - fileserver
    - fileserver.zfs
  when: fileserver_setup_zfs is true
  block:
    # Setup ZFS
    - name: Setup ZFS
      ansible.builtin.include_tasks: setup_zfs.yaml

    # Setup ZFS pool
    - name: Setup ZFS pool
      ansible.builtin.include_tasks: setup_zfs_pool.yaml
      vars:
        fileserver_zfs_pool: "{{ item }}"
      loop: "{{ fileserver_zfs_pools }}"
      loop_control:
        label: "{{ item.pool_name }}"

    # Setup ZFS datasets
    - name: Setup ZFS datasets
      ansible.builtin.include_tasks: setup_zfs_datasets.yaml
      vars:
        fileserver_zfs_pool: "{{ item }}"
      loop: "{{ fileserver_zfs_pools }}"
      loop_control:
        label: "{{ item.pool_name }}"
      when: item.datasets is defined and item.datasets | length > 0

# Setup the NFS server
- name: Setup the NFS server
  ansible.builtin.include_tasks: setup_nfs_server.yaml
  when: fileserver_setup_nfs_server is true
  tags:
    - fileserver
    - fileserver.nfs-server

# Flush handlers to apply NFS exports
- name: Flush handlers to apply NFS exports
  ansible.builtin.meta: flush_handlers

# Setup the NFS client
- name: Setup the NFS client
  ansible.builtin.include_tasks: setup_nfs_client.yaml
  when: fileserver_setup_nfs_client is true
  tags:
    - fileserver
    - fileserver.nfs-client
