---
# main tasks file for the fileserver role
#
# inputs:
#   - fileserver_setup_mergerfs: boolean
#   - fileserver_install_nfs_server: boolean
#   - fileserver_install_nfs_client: boolean

# Setup mergerfs
- name: Block for mergerfs tasks
  tags:
    - fileserver
    - fileserver.mergerfs
    - fileserver.ext4
  when: fileserver_setup_mergerfs is true
  block:
    # Setup required disks with ext4 filesystem
    - name: Setup required disks with ext4 filesystem
      ansible.builtin.include_tasks: setup_ext4.yaml
      vars:
        fileserver_ext4_disks: "{{ fileserver_mergerfs_disks }}"

    # Setup mergerfs
    - name: Setup mergerfs
      ansible.builtin.include_tasks: setup_mergerfs.yaml

# Setup SnapRAID and SnapRAID aio
- name: Setup SnapRAID and SnapRAID aio
  tags:
    - fileserver
    - fileserver.snapraid
  when: fileserver_setup_snapraid is true
  block:
    # Setup SnapRAID
    - name: Setup SnapRAID
      ansible.builtin.include_tasks: setup_snapraid.yaml

# Setup the NFS server
- name: Setup the NFS server
  ansible.builtin.include_tasks: setup_nfs_server.yaml
  when: fileserver_install_nfs_server is true
  tags:
    - fileserver
    - fileserver.nfs-server

# Flush handlers to apply NFS exports
- name: Flush handlers to apply NFS exports
  ansible.builtin.meta: flush_handlers

# Setup the NFS client
- name: Setup the NFS client
  ansible.builtin.include_tasks: setup_nfs_client.yaml
  when: fileserver_install_nfs_client is true
  tags:
    - fileserver
    - fileserver.nfs-client
