---
# Tasks to setup ZFS datasets on a host.
#
# Input variables:
#   fileserver_zfs_pool:
#     pool_name: <name of the ZFS pool>
#     datasets:
#       - name: <name of the ZFS dataset>
#         mount_point: <mount point for the dataset>
#         quota: <quota for the dataset>
#     # other ZFS dataset properties not used in this task

# block for ZFS datasets tasks
- name: Block for ZFS datasets tasks
  tags:
    - fileserver
    - fileserver.zfs
  block:

    # Check if the ZFS dataset exists
    - name: Check if the ZFS dataset exists
      ansible.builtin.command: >
        zfs list -H "{{ dataset.name }}"
      register: zfs_dataset_check
      loop: "{{ fileserver_zfs_pool.datasets }}"
      loop_control:
        loop_var: dataset
      changed_when: false
      failed_when: false

    # Create the ZFS dataset if it does not exist
    - name: Create the ZFS dataset if it does not exist
      ansible.builtin.command: >
        zfs create
        -o mountpoint="{{ result.dataset.mount_point }}"
        -o compression=lz4
        -o xattr=sa
        -o normalization=formD
        -o quota="{{ result.dataset.quota }}"
        "{{ result.dataset.name }}"
      loop: "{{ zfs_dataset_check.results }}"
      loop_control:
        loop_var: result
        label: "{{ result.dataset.name }}"
      when: result.rc != 0
      changed_when: result.rc != 0
      become: true

    # Set the dataset mount permissions
    - name: Set the dataset mount permissions
      ansible.builtin.file:
        path: "{{ dataset.mount_point }}"
        owner: "{{ default_user }}"
        group: "{{ default_user }}"
        state: directory
        mode: "0755"
      loop: "{{ fileserver_zfs_pool.datasets }}"
      loop_control:
        loop_var: dataset
        label: "{{ dataset.name }}"
      become: true
