---
# tasks to setup nfs server on a host.

# block for nfs server tasks
- name: Block for nfs server tasks
  tags:
    - fileserver
    - fileserver.nfs
  block:
    # install nfs server
    - name: Install nfs server
      ansible.builtin.apt:
        pkg:
          - nfs-kernel-server
        state: present
      become: true

    # ensure /export root directory exists
    - name: Ensure /export root directory exists
      ansible.builtin.file:
        path: /export
        state: directory
        owner: root
        group: root
        mode: '0755'
      become: true

    # create bind-mount directories for exports
    - name: Ensure /export subdirs exist
      ansible.builtin.file:
        path: "{{ item.alias }}"
        state: directory
        owner: root
        group: root
        mode: "{{ item.mode | default('0755') }}"
      loop: "{{ fileserver_nfs_exports }}"
      become: true

    # bind mount ZFS datasets → /export/...
    - name: Create bind mounts for export aliases
      ansible.posix.mount:
        src: "{{ item.src }}"
        path: "{{ item.alias }}"
        fstype: none
        opts: bind
        state: mounted
      loop: "{{ fileserver_nfs_exports }}"
      become: true

    # configure exports file
    - name: Configure exports file
      ansible.builtin.template:
        src: exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: '0644'
      vars:
        nfs_exports: "{{ fileserver_nfs_exports }}"
      become: true
      notify: Apply nfs exports
