---
# Tasks to properly setup and mount disks
#
# inputs:
#   - fileserver_attached_disks: disk to setup

# Setup attached disks with ext4 filesystem
- name: Setup attached disks with ext4 filesystem
  tags:
    - fileserver
    - fileserver.ext4
  when: fileserver_setup_attached_disks is true and
        fileserver_attached_disks is defined
  block:
    # Setup required disks with ext4 filesystem
    - name: Setup required disks with ext4 filesystem
      ansible.builtin.include_tasks: setup_ext4.yaml
      vars:
        fileserver_ext4_disks: "{{ fileserver_attached_disks }}"

    # Mount the attached disks
    - name: Mount the attached disks
      ansible.posix.mount:
        src: "/dev/disk/by-id/{{ item.name }}-part1"
        path: "{{ item.mount_point }}"
        opts: "{{ item.options | default(omit) }}"
        state: "{{ item.state }}"
        fstype: "{{ item.filesystem_type }}"
      loop: "{{ fileserver_attached_disks }}"
      become: true

    # Set the permissions for the mount points of the attached disks
    - name: Set the permissions for the mount points
      ansible.builtin.file:
        path: "{{ item.mount_point }}"
        state: directory
        mode: "0755"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
      loop: "{{ fileserver_attached_disks }}"
      become: true
