---
# The main task file for the ntfy role
#
# This role assumes that ntfy is installed via docker and that the ntfy container is running.

# Check if the ntfy user is already created
- name: Check if the ntfy user is already created
  community.docker.docker_container_exec:
    container: ntfy
    command: ntfy user list
  register: ntfy_user_list
  changed_when: false
  tags:
    - ntfy

# Create the ntfy user
- name: Create the ntfy user
  community.docker.docker_container_exec:
    container: ntfy
    command: ntfy user add --role admin "{{ ntfy_user }}"
    env:
      NTFY_PASSWORD: "{{ ntfy_password }}"
  register: ntfy_user_add
  changed_when: ntfy_user_add.stdout.find('User added') != -1
  when: ntfy_user_list.stderr.find(ntfy_user) == -1
  tags:
    - ntfy

# Call the tokens task to extract the tokens
- name: Extract the ntfy tokens
  ansible.builtin.include_tasks: tokens.yaml
  tags:
    - ntfy

# Create the ntfy tokens if they do not exist
- name: Create the ntfy tokens
  community.docker.docker_container_exec:
    container: ntfy
    command: ntfy token add --label "{{ token.label }}" "{{ ntfy_user }}"
  loop: "{{ ntfy_tokens }}"
  loop_control:
    loop_var: token
    label: "{{ token.label }}"
  register: ntfy_token_add
  when: token.label not in ntfy_tokens_extracted.keys()
  changed_when: token.label not in ntfy_tokens_extracted.keys()

  tags:
    - ntfy
