---
# The main task file for the ntfy role
#
# This role assumes that ntfy is installed via docker and that the ntfy container is running.

# Check if the ntfy user is already created
- name: Check if the ntfy user is already created
  community.docker.docker_container_exec:
    container: ntfy
    command: ntfy user list
  register: ntfy_user_list
  changed_when: false
  tags:
    - ntfy

# Create the ntfy user
- name: Create the ntfy user
  community.docker.docker_container_exec:
    container: ntfy
    command: ntfy user add --role admin "{{ ntfy_user }}"
    env:
      NTFY_PASSWORD: "{{ ntfy_password }}"
  register: ntfy_user_add
  changed_when: ntfy_user_add.stdout.find('User added') != -1
  when: ntfy_user_list.stderr.find(ntfy_user) == -1
  tags:
    - ntfy
