---
# Docker host variables for docker-02.home.stechsolutions.ca host

# other variables are set in group_vars/proxmox_vms.yaml and
# promox_vms/docker_hosts.yaml

# lubelogger setup
vehicle_db_name: vehicle
vehicle_db_user: vehicle_user
vehicle_db_password: vehicle_password
vehicle_connection_string: "Host=postgres_vehicle_db:5432;Database={{ vehicle_db_name }};Username={{ vehicle_db_user }};Password={{ vehicle_db_password }}"

# wud configuration
wud_trigger_ntfy_sh_url: https://ntfy.stechsolutions.ca
wud_trigger_ntfy_sh_topic: wud
wud_trigger_ntfy_sh_priority: 2
wud_trigger_ntfy_sh_auth_user: "{{ default_user }}"
wud_trigger_ntfy_sh_auth_password: "{{ secret_ntfy_password }}"

# docker container configuration files
docker_configuration_files:
  - name: traefik.yaml
    src: "{{ inventory_dir }}/../files/traefik/traefik-prod.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/traefik/traefik.yaml
    mode: '0664'
    container_name: traefik
  - name: unifi.yaml
    src: "{{ inventory_dir }}/../files/traefik/dynamic/unifi.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/traefik/dynamic/unifi.yaml
    mode: '0664'
    container_name: traefik
  - name: homepage_settings.yaml
    src: "{{ inventory_dir }}/../files/homepage/settings.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage/settings.yaml
    mode: '0664'
    container_name: homepage
  - name: homepage_bookmarks.yaml
    src: "{{ inventory_dir }}/../files/homepage/bookmarks.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage/bookmarks.yaml
    mode: '0664'
    container_name: homepage
  - name: homepage_docker.yaml
    src: "{{ inventory_dir }}/../files/homepage/docker.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage/docker.yaml
    mode: '0664'
    container_name: homepage

# docker container template files
docker_template_files:
  - name: homepage_widgets.yaml
    src: "{{ inventory_dir }}/../files/homepage/widgets.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage/widgets.yaml
    mode: '0664'
    container_name: homepage
  - name: homepage_services.yaml
    src: "{{ inventory_dir }}/../files/homepage/services.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage/services.yaml
    mode: '0664'
    container_name: homepage

# docker mounts subfolders
docker_mounts_subfolders:
  - name: postgres_vehicle
    dest: /home/{{ default_user }}/docker_mounts/vehicle/postgres
    mode: '0775'
    container_name: postgres_vehicle_db
  - name: lubelogger_config
    dest: /home/{{ default_user }}/docker_mounts/vehicle/lubelogger/config
    mode: '0775'
    container_name: lubelogger
  - name: lubelogger_data
    dest: /home/{{ default_user }}/docker_mounts/vehicle/lubelogger/data
    mode: '0775'
    container_name: lubelogger
  - name: lubelogger_documents
    dest: /home/{{ default_user }}/docker_mounts/vehicle/lubelogger/documents
    mode: '0775'
    container_name: lubelogger
  - name: lubelogger_images
    dest: /home/{{ default_user }}/docker_mounts/vehicle/lubelogger/images
    mode: '0775'
    container_name: lubelogger
  - name: lubelogger_log
    dest: /home/{{ default_user }}/docker_mounts/vehicle/lubelogger/log
    mode: '0775'
    container_name: lubelogger
  - name: lubelogger_temp
    dest: /home/{{ default_user }}/docker_mounts/vehicle/lubelogger/temp
    mode: '0775'
    container_name: lubelogger
  - name: lubelogger_translations
    dest: /home/{{ default_user }}/docker_mounts/vehicle/lubelogger/translations
    mode: '0775'
    container_name: lubelogger
  - name: lubelogger_keys
    dest: /home/{{ default_user }}/docker_mounts/vehicle/lubelogger/keys
    mode: '0775'
    container_name: lubelogger

# docker compose
docker_compose:
  - compose_name: proxy
    state: present
    networks:
      traefik:
        name: traefik
      docker-proxy:
        name: docker-proxy
    containers:
      - container_name: traefik
        image: traefik:v3.1
        networks:
          - traefik
          - docker-proxy
        environment:
          - TZ=America/Edmonton
          - "CF_API_EMAIL={{ default_user_email }}"
          - "CF_DNS_API_TOKEN={{ secret_cf_token }}"
        ports:
          - 80:80
          - 443:443
        depends_on:
          - docker-socket-proxy
        volumes:
          - "/home/{{ default_user }}/docker_mounts/proxy/traefik:/etc/traefik"
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.dashboard.rule=Host(`docker-02.home.stechsolutions.ca`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
          - "traefik.http.routers.dashboard.service=api@internal"
          - "traefik.http.routers.dashboard.middlewares=auth"
          - "traefik.http.middlewares.auth.basicauth.users={{ default_user }}:{{ secret_traefik_dashboard_password_hash }}"
          - "traefik.http.routers.dashboard.entrypoints=websecure"
          - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
          - "homepage.group=Proxy"
          - "homepage.name=Traefik"
          - "homepage.description=Reverse Proxy"
          - "homepage.icon=traefik.png"
          - "homepage.href=https://docker-02.home.stechsolutions.ca/dashboard/#/"
          - "homepage.siteMonitor=https://docker-02.home.stechsolutions.ca/dashboard/#/"
          - "homepage.widget.type=traefik"
          - "homepage.widget.url=https://docker-02.home.stechsolutions.ca"
          - "homepage.widget.username={{ default_user }}"
          - "homepage.widget.password={{ secret_traefik_dashboard_password }}"
          - "homepage.widget.routers="
          - "homepage.widget.services="
          - "homepage.widget.middleware="
          - "wud.tag.include=^v?\\d+\\.\\d+\\.\\d+$"
          - "wud.link.template=https://github.com/traefik/traefik/releases"
      - container_name: docker-socket-proxy
        image: tecnativa/docker-socket-proxy:0.2.0
        networks:
          - docker-proxy
        environment:
          - CONTAINERS=1 # Allow access to viewing containers
          - IMAGES=1 # Allow access to viewing images
          - POST=0 # Disallow any POST operations (effectively read-only)
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        restart: unless-stopped
        labels:
          - "wud.tag.include=^v?\\d+\\.\\d+\\.\\d+$"
          - "wud.link.template=https://github.com/Tecnativa/docker-socket-proxy/releases"
      - container_name: homepage
        image: ghcr.io/gethomepage/homepage:v0.9.11
        networks:
          - traefik
          - docker-proxy
        depends_on:
          - docker-socket-proxy
        environment:
          - TZ=America/Edmonton
          - PUID=1000
          - PGID=1000
        volumes:
          - "/home/{{ default_user }}/docker_mounts/proxy/homepage:/app/config"
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.homepage.rule=Host(`homepage.home.stechsolutions.ca`)"
          - "traefik.http.services.homepage.loadbalancer.server.port=3000"
          - "traefik.http.routers.homepage.entrypoints=websecure"
          - "traefik.http.routers.homepage.tls.certresolver=letsencrypt"
          - "wud.tag.include=^v?\\d+\\.\\d+\\.\\d+$"
          - "wud.link.template=https://github.com/gethomepage/homepage/releases"
  - compose_name: tdarr
    state: present
    networks:
      traefik:
        name: traefik
        external: true
    containers:
      - container_name: tdarr
        image: haveagitgat/tdarr:2.23.01
        networks:
          - traefik
        environment:
          - TZ=America/Edmonton
          - PUID=1000
          - PGID=1000
          - UMASK_SET=022
          - serverIP=0.0.0.0
          - serverPort=8266
          - webUIPort=8265
          - internalNode=true
          - inContainer=true
          - ffmpegVersion=6
          - nodeName=MyInternalNode
        volumes:
          - "/mnt/scratch/tdarr:/temp"
          - "/mnt/nfs/movies:/movies"
          - "/mnt/nfs/tv:/tv"
          - "/home/{{ default_user }}/docker_mounts/tdarr/server:/app/server"
          - "/home/{{ default_user }}/docker_mounts/tdarr/configs:/app/configs"
          - "/home/{{ default_user }}/docker_mounts/tdarr/logs:/app/logs"
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.tdarr.rule=Host(`tdarr.home.stechsolutions.ca`)"
          - "traefik.http.services.tdarr.loadbalancer.server.port=8265"
          - "traefik.http.routers.tdarr.entrypoints=websecure"
          - "traefik.http.routers.tdarr.tls.certresolver=letsencrypt"
          - "homepage.group=Media"
          - "homepage.name=Tdarr"
          - "homepage.description=Transcoding System"
          - "homepage.icon=tdarr.png"
          - "homepage.href=https://tdarr.home.stechsolutions.ca"
          - "homepage.siteMonitor=https://tdarr.home.stechsolutions.ca"
          - "homepage.widget.type=tdarr"
          - "homepage.widget.url=https://tdarr.home.stechsolutions.ca"
          - "wud.tag.include=^v?\\d+\\.\\d+\\.\\d+$"
          - "wud.link.template=https://home.tdarr.io/download"
  - compose_name: vehicle
    state: present
    networks:
      traefik:
        name: traefik
        external: true
      vehicle_postgres:
        name: vehicle_postgres
    containers:
      - container_name: postgres_vehicle_db
        image: postgres:17.1
        user: 1000:1000
        networks:
          - vehicle_postgres
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U {{ vehicle_db_user }} -d {{ vehicle_db_name }}"]
          interval: 60s
          timeout: 10s
          retries: 3
          start_period: 40s
        environment:
          - POSTGRES_DB={{ vehicle_db_name }}
          - POSTGRES_USER={{ vehicle_db_user }}
          - POSTGRES_PASSWORD={{ vehicle_db_password }}
        volumes:
          - "/home/{{ default_user }}/docker_mounts/vehicle/postgres:/var/lib/postgresql/data"
          - "/etc/passwd:/etc/passwd:ro"
        restart: unless-stopped
        labels:
          - "wud.tag.include=^v?\\d+\\.\\d+\\.\\d+$"
          - "wud.link.template=https://www.postgresql.org/docs/release/"
      - container_name: lubelogger
        image: hargata/lubelogger:v1.3.9
        user: 1000:1000
        networks:
          - traefik
          - vehicle_postgres
        environment:
          - LC_ALL=en_US.UTF-8
          - LANG=en_US.UTF-8
          - POSTGRES_CONNECTION={{ vehicle_connection_string }}
        volumes:
          - "/home/{{ default_user }}/docker_mounts/vehicle/lubelogger/config:/App/config"
          - "/home/{{ default_user }}/docker_mounts/vehicle/lubelogger/data:/App/data"
          - "/home/{{ default_user }}/docker_mounts/vehicle/lubelogger/translations:/App/wwwroot/translations"
          - "/home/{{ default_user }}/docker_mounts/vehicle/lubelogger/documents:/App/wwwroot/documents"
          - "/home/{{ default_user }}/docker_mounts/vehicle/lubelogger/images:/App/wwwroot/images"
          - "/home/{{ default_user }}/docker_mounts/vehicle/lubelogger/temp:/App/wwwroot/temp"
          - "/home/{{ default_user }}/docker_mounts/vehicle/lubelogger/log:/App/log"
          - "/home/{{ default_user }}/docker_mounts/vehicle/lubelogger/keys:/root/.aspnet/DataProtection-Keys"
        depends_on:
          - postgres_vehicle_db
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.lubelogger.rule=Host(`lubelogger.home.stechsolutions.ca`)"
          - "traefik.docker.network=traefik"
          - "traefik.http.services.lubelogger.loadbalancer.server.port=8080"
          - "traefik.http.routers.lubelogger.entrypoints=websecure"
          - "traefik.http.routers.lubelogger.tls.certresolver=letsencrypt"
          - "homepage.group=Vehicle"
          - "homepage.name=Lubelogger"
          - "homepage.description=Vehicle Logging"
          - "homepage.icon=lubelogger.png"
          - "homepage.href=https://lubelogger.home.stechsolutions.ca"
          - "homepage.siteMonitor=https://lubelogger.home.stechsolutions.ca"
          - "homepage.widget.type=lubelogger"
          - "homepage.widget.url=https://lubelogger.home.stechsolutions.ca"
          - "wud.tag.include=^v?\\d+\\.\\d+\\.\\d+$"
          - "wud.link.template=https://github.com/hargata/lubelog/releases"
  - compose_name: wud
    state: present
    networks:
      traefik:
        name: traefik
        external: true
      docker-proxy:
        name: docker-proxy
        external: true
    containers:
      - container_name: wud
        image: getwud/wud:7.1.1
        networks:
          - traefik
          - docker-proxy
        environment:
          - WUD_TRIGGER_NTFY_SELFHOSTED_URL={{ wud_trigger_ntfy_sh_url }}
          - WUD_TRIGGER_NTFY_SELFHOSTED_TOPIC={{ wud_trigger_ntfy_sh_topic }}
          - WUD_TRIGGER_NTFY_SELFHOSTED_PRIORITY={{ wud_trigger_ntfy_sh_priority }}
          - WUD_TRIGGER_NTFY_SELFHOSTED_AUTH_USER={{ wud_trigger_ntfy_sh_auth_user }}
          - WUD_TRIGGER_NTFY_SELFHOSTED_AUTH_PASSWORD={{ wud_trigger_ntfy_sh_auth_password }}
          - WUD_TRIGGER_NTFY_SELFHOSTED_MODE=batch
          - WUD_TRIGGER_NTFY_SELFHOSTED_ONCE=true
          - WUD_WATCHER_LOCAL_HOST=docker-socket-proxy
          - WUD_WATCHER_LOCAL_WATCHEVENTS=false
          - WUD_WATCHER_LOCAL_WATCHATSTART=false
          - WUD_WATCHER_LOCAL_CRON=0 */6 * * *
          - WUD_WATCHER_DOCKERCLOUD01_HOST=docker-cloud-01.tailfacdb.ts.net
          - WUD_WATCHER_DOCKERCLOUD01_WATCHEVENTS=false
          - WUD_WATCHER_DOCKERCLOUD01_WATCHATSTART=false
          - WUD_WATCHER_DOCKERCLOUD01_CRON=0 */6 * * *
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.wud.rule=Host(`wud.home.stechsolutions.ca`)"
          - "traefik.http.services.wud.loadbalancer.server.port=3000"
          - "traefik.http.routers.wud.entrypoints=websecure"
          - "traefik.http.routers.wud.tls.certresolver=letsencrypt"
          - "homepage.group=Monitoring"
          - "homepage.name=WUD"
          - "homepage.description=What's Up Docker"
          - "homepage.icon=wud.png"
          - "homepage.href=https://wud.home.stechsolutions.ca"
          - "homepage.siteMonitor=https://wud.home.stechsolutions.ca"
          - "homepage.widget.type=whatsupdocker"
          - "homepage.widget.url=https://wud.home.stechsolutions.ca"
          - "wud.tag.include=^v?\\d+\\.\\d+\\.\\d+$"
          - "wud.link.template=https://github.com/getwud/wud/releases"
