---
# Docker host variables for docker-02.home.stechsolutions.ca host

# other variables are set in group_vars/proxmox_vms.yaml and
# promox_vms/docker_hosts.yaml

# lubelogger setup
vehicle_db_name: vehicle
vehicle_db_user: vehicle_user
vehicle_db_password: vehicle_password
vehicle_connection_string: "Host=postgres_vehicle_db:5432;Database={{ vehicle_db_name }};Username={{ vehicle_db_user }};Password={{ vehicle_db_password }}"

# wud configuration
wud_trigger_ntfy_sh_url: https://ntfy.stechsolutions.ca
wud_trigger_ntfy_sh_topic: wud
wud_trigger_ntfy_sh_priority: 2
wud_trigger_ntfy_sh_auth_user: "{{ default_user }}"
wud_trigger_ntfy_sh_auth_password: "{{ secret_ntfy_password }}"

# docker container paths. All found files will be processed and copied to the docker host
docker_configuration_paths:
  - name: homepage
    src: /home/nelson/GitHub/infrastructure/files/homepage
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage
    mode: '0664'
    container_name: homepage
  - name: prometheus
    src: /home/nelson/GitHub/infrastructure/files/prometheus
    dest: /home/{{ default_user }}/docker_mounts/monitoring/prometheus
    mode: '0664'
    container_name: prometheus
  - name: grafana
    src: /home/nelson/GitHub/infrastructure/files/grafana
    dest: /home/{{ default_user }}/docker_mounts/monitoring/grafana
    mode: '0664'
    container_name: grafana

# docker container configuration files
docker_configuration_files:
  # traefik configuration file
  - name: traefik.yaml
    src: "{{ inventory_dir }}/../files/traefik/traefik-prod.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/traefik/traefik.yaml
    mode: '0664'
    container_name: traefik
  - name: unifi.yaml
    src: "{{ inventory_dir }}/../files/traefik/dynamic/unifi.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/traefik/dynamic/unifi.yaml
    mode: '0664'
    container_name: traefik
  # prometheus configuration files
  - name: prometheus_alertmanager_config.yaml
    src: "{{ inventory_dir }}/../files/alertmanager/alertmanager.yaml.j2"
    dest: /home/{{ default_user }}/docker_mounts/monitoring/alertmanager/alertmanager.yml
    mode: '0664'
    container_name: alertmanager
  - name: prometheus_alertmanager_ntfy_config.yaml
    src: "{{ inventory_dir }}/../files/ntfy-alertmanager/ntfy-alertmanager_config.scfg.j2"
    dest: /home/{{ default_user }}/docker_mounts/monitoring/ntfy-alertmanager/config
    mode: '0664'
    container_name: ntfy-alertmanager

# docker mounts subfolders
docker_mounts_subfolders:
  # vehicle docker mounts
  - name: postgres_vehicle
    dest: /home/{{ default_user }}/docker_mounts/vehicle/postgres
    mode: '0775'
    container_name: postgres_vehicle_db
  - name: lubelogger_data
    dest: /home/{{ default_user }}/docker_mounts/vehicle/lubelogger/data
    mode: '0775'
    container_name: lubelogger
  - name: lubelogger_keys
    dest: /home/{{ default_user }}/docker_mounts/vehicle/lubelogger/keys
    mode: '0775'
    container_name: lubelogger
  # prometheus docker mounts
  - name: monitoring_prometheus
    dest: /home/{{ default_user }}/docker_mounts/monitoring/prometheus/data
    mode: '0775'
    container_name: prometheus
  # grafana docker mounts
  - name: monitoring_grafana
    dest: /home/{{ default_user }}/docker_mounts/monitoring/grafana/data
    mode: '0775'
    container_name: grafana
  # filestash docker mounts
  - name: files_filestash
    dest: /home/{{ default_user }}/docker_mounts/files/filestash
    mode: '0775'
    container_name: filestash

docker_compose_subpath: "{{ inventory_dir }}/host_vars/docker-02.home.stechsolutions.ca/docker_compose"

# docker compose template files
docker_compose_files:
  - name: monitoring-docker-compose.yaml
    compose_name: monitoring
    state: present
    src: "{{ docker_compose_subpath }}/monitoring.yaml.j2"
    dest: /home/{{ default_user }}/docker_compose/monitoring-docker-compose.yaml
    mode: '0664'
  - name: proxy-docker-compose.yaml
    compose_name: proxy
    state: present
    src: "{{ docker_compose_subpath }}/proxy.yaml.j2"
    dest: /home/{{ default_user }}/docker_compose/proxy-docker-compose.yaml
    mode: '0664'
  - name: tdarr-docker-compose.yaml
    compose_name: tdarr
    state: present
    src: "{{ docker_compose_subpath }}/tdarr.yaml.j2"
    dest: /home/{{ default_user }}/docker_compose/tdarr-docker-compose.yaml
    mode: '0664'
  - name: vehicle-docker-compose.yaml
    compose_name: vehicle
    state: present
    src: "{{ docker_compose_subpath }}/vehicle.yaml.j2"
    dest: /home/{{ default_user }}/docker_compose/vehicle-docker-compose.yaml
    mode: '0664'
  - name: wud-docker-compose.yaml
    compose_name: wud
    state: present
    src: "{{ docker_compose_subpath }}/wud.yaml.j2"
    dest: /home/{{ default_user }}/docker_compose/wud-docker-compose.yaml
    mode: '0664'
  - name: files-docker-compose.yaml
    compose_name: files
    state: present
    src: "{{ docker_compose_subpath }}/files.yaml.j2"
    dest: /home/{{ default_user }}/docker_compose/files-docker-compose.yaml
    mode: '0664'
