---
# Fileserver host variables for docker-02.home.stechsolutions.ca host

# other variables are set in group_vars/proxmox_vms.yaml and
# promox_vms/docker_hosts.yaml

fileserver_setup: true
fileserver_setup_nfs_client: true
fileserver_setup_attached_disks: true

fileserver_attached_disks:
  # 50 GB disk for tdarr scratch space
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
    partition_label: 50-GB-VD-0
    mount_point: "/mnt/scratch/tdarr"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted
  # 10 GB disk for docker compose proxy volume
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi2
    partition_label: 10-GB-VD-0
    mount_point: "/home/{{ default_user }}/docker_mounts/proxy"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted
  # 10 GB disk for docker compose tdarr volume
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi3
    partition_label: 10-GB-VD-0
    mount_point: "/home/{{ default_user }}/docker_mounts/tdarr"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted
  # 5 GB disk for docker compose vehicle volume
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi4
    partition_label: 5-GB-VD-0
    mount_point: "/home/{{ default_user }}/docker_mounts/vehicle"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted
  # 10 GB disk for docker mounts montoring volume
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi5
    partition_label: 10-GB-VD-1
    mount_point: "/home/{{ default_user }}/docker_mounts/monitoring"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted
  # 5 GB disk for docker mounts file volume
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi6
    partition_label: 5-GB-VD-1
    mount_point: "/home/{{ default_user }}/docker_mounts/files"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted

fileserver_nfs_mounts:
  - path: /mnt/nfs/movies
    server: storage.home.stechsolutions.ca
    nfs_export: /mnt/storage/movies
    options: defaults
    state: mounted
  - path: /mnt/nfs/tv
    server: storage.home.stechsolutions.ca
    nfs_export: /mnt/storage/tv
    options: defaults
    state: mounted
