---
# Configuration for Tailscale

# tailscale
tailscale_setup: true
tailscale_authkey: "{{ secret_ts_client_secret }}?ephemeral=false&preauthorized=true"
tailscale_args: |
  --advertise-tags='tag:server'
  --accept-dns
