---
# docker variables for docker-testing.home.stechsolutions.ca host

# docker container configuration files
docker_configuration_files:
  # traefik configuration file
  - name: traefik.yaml
    src: "{{ inventory_dir }}/../files/traefik/traefik-dev.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/traefik/traefik.yaml
    mode: '0664'
    container_name: traefik
  - name: unifi.yaml
    src: "{{ inventory_dir }}/../files/traefik/dynamic/unifi.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/traefik/dynamic/unifi.yaml
    mode: '0664'
    container_name: traefik
  # homepage configuration files
  - name: homepage_settings.yaml
    src: "{{ inventory_dir }}/../files/homepage/settings.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage/settings.yaml
    mode: '0664'
    container_name: homepage
  - name: homepage_bookmarks.yaml
    src: "{{ inventory_dir }}/../files/homepage/bookmarks.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage/bookmarks.yaml
    mode: '0664'
    container_name: homepage
  - name: homepage_docker.yaml
    src: "{{ inventory_dir }}/../files/homepage/docker.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage/docker.yaml
    mode: '0664'
    container_name: homepage

# docker container template files
docker_template_files:
  # homepage configuration files
  - name: homepage_widgets.yaml
    src: "{{ inventory_dir }}/../files/homepage/widgets.yaml.j2"
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage/widgets.yaml
    mode: '0664'
    container_name: homepage
  - name: homepage_services.yaml
    src: "{{ inventory_dir }}/../files/homepage/services.yaml.j2"
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage/services.yaml
    mode: '0664'
    container_name: homepage

# docker mounts subfolders
# docker_mounts_subfolders:

docker_compose_subpath: "{{ inventory_dir }}/host_vars/docker-testing.home.stechsolutions.ca/docker_compose"

# docker compose template files
docker_compose_files:
  - name: proxy-docker-compose.yaml
    compose_name: proxy
    state: present
    src: "{{ docker_compose_subpath }}/proxy.yaml.j2"
    dest: /home/{{ default_user }}/docker_compose/proxy-docker-compose.yaml
    mode: '0664'
