---
# docker variables for docker-testing.home.stechsolutions.ca host

# docker container configuration files
docker_configuration_files:
  - name: traefik.yaml
    src: "{{ inventory_dir }}/../files/traefik/traefik-dev.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/traefik/traefik.yaml
    mode: '0664'
    container_name: traefik
  - name: unifi.yaml
    src: "{{ inventory_dir }}/../files/traefik/dynamic/unifi.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/traefik/dynamic/unifi.yaml
    mode: '0664'
    container_name: traefik
  - name: homepage_settings.yaml
    src: "{{ inventory_dir }}/../files/homepage/settings.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage/settings.yaml
    mode: '0664'
    container_name: homepage
  - name: homepage_bookmarks.yaml
    src: "{{ inventory_dir }}/../files/homepage/bookmarks.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage/bookmarks.yaml
    mode: '0664'
    container_name: homepage
  - name: homepage_docker.yaml
    src: "{{ inventory_dir }}/../files/homepage/docker.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage/docker.yaml
    mode: '0664'
    container_name: homepage
  - name: prometheus_config.yaml
    src: "{{ inventory_dir }}/../files/prometheus/prometheus.yaml"
    dest: /home/{{ default_user }}/docker_mounts/monitoring/prometheus/prometheus.yml
    mode: '0664'
    container_name: prometheus
  - name: prometheus_rules.yaml
    src: "{{ inventory_dir }}/../files/prometheus/rules/alerts.yaml"
    dest: /home/{{ default_user }}/docker_mounts/monitoring/prometheus/rules/alerts.yaml
    mode: '0664'
    container_name: prometheus
  - name: prometheus_rules_test.yaml
    src: "{{ inventory_dir }}/../files/prometheus/rules/test.yaml"
    dest: /home/{{ default_user }}/docker_mounts/monitoring/prometheus/rules/test.yaml
    mode: '0664'
    container_name: prometheus

# docker container template files
docker_template_files:
  - name: homepage_widgets.yaml
    src: "{{ inventory_dir }}/../files/homepage/widgets.yaml.j2"
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage/widgets.yaml
    mode: '0664'
    container_name: homepage
  - name: homepage_services.yaml
    src: "{{ inventory_dir }}/../files/homepage/services.yaml.j2"
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage/services.yaml
    mode: '0664'
    container_name: homepage
  - name: prometheus_targets.yaml
    src: "{{ inventory_dir }}/../files/prometheus/targets/nodes.yaml.j2"
    dest: /home/{{ default_user }}/docker_mounts/monitoring/prometheus/targets/nodes.yaml
    mode: '0664'
    container_name: prometheus

# docker mounts subfolders
docker_mounts_subfolders:
  - name: monitoring_prometheus
    dest: /home/{{ default_user }}/docker_mounts/monitoring/prometheus/data
    mode: '0775'
    container_name: prometheus

docker_compose_subpath: "{{ inventory_dir }}/host_vars/docker-testing.home.stechsolutions.ca/docker_compose"

# docker compose template files
docker_compose_files:
  - name: monitoring-docker-compose.yaml
    compose_name: monitoring
    state: present
  - compose_name: monitoring
    src: "{{ docker_compose_subpath }}/monitoring.yaml.j2"
    dest: /home/{{ default_user }}/docker_compose/monitoring-docker-compose.yaml
    mode: '0664'
    state: present
    networks:
      traefik:
        name: traefik
        external: true
    containers:
      - container_name: prometheus
        image: prom/prometheus:v3.0.1
        command:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--web.external-url=http://prometheus-testing.home.stechsolutions.ca"
        user: "1000:1000"
        networks:
          - traefik
        healthcheck:
          test: ["CMD", "promtool", "check", "healthy"]
          interval: 30s
          timeout: 10s
          retries: 3
        volumes:
          - "/home/{{ default_user }}/docker_mounts/monitoring/prometheus:/etc/prometheus"
          - "/home/{{ default_user }}/docker_mounts/monitoring/prometheus/data:/prometheus"
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.prometheus.rule=Host(`prometheus-testing.home.stechsolutions.ca`)"
          - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
          - "traefik.http.routers.prometheus.entrypoints=websecure"
          - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"
