---
# docker variables for docker-testing.home.stechsolutions.ca host

# docker container paths. All found files will be processed and copied to the docker host
docker_configuration_paths:
  - name: homepage
    src: /home/nelson/GitHub/infrastructure/files/homepage
    dest: /home/{{ default_user }}/docker_mounts/proxy/homepage
    mode: '0664'
    container_name: homepage

# docker container configuration files
docker_configuration_files:
  # traefik configuration file
  - name: traefik.yaml
    src: "{{ inventory_dir }}/../files/traefik/traefik-dev.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/traefik/traefik.yaml
    mode: '0664'
    container_name: traefik
  - name: unifi.yaml
    src: "{{ inventory_dir }}/../files/traefik/dynamic/unifi.yaml"
    dest: /home/{{ default_user }}/docker_mounts/proxy/traefik/dynamic/unifi.yaml
    mode: '0664'
    container_name: traefik

# docker mounts subfolders
# docker_mounts_subfolders:

docker_compose_subpath: "{{ inventory_dir }}/host_vars/docker-testing.home.stechsolutions.ca/docker_compose"

# docker compose template files
docker_compose_files:
  - name: proxy-docker-compose.yaml
    compose_name: proxy
    state: present
    src: "{{ docker_compose_subpath }}/proxy.yaml.j2"
    dest: /home/{{ default_user }}/docker_compose/proxy-docker-compose.yaml
    mode: '0664'
