# Fileserver host variables for docker-testing.home.stechsolutions.ca host

# other variables are set in group_vars/proxmox_vms.yaml and
# proxmox_vms/docker_hosts.yaml

fileserver_setup: true
fileserver_setup_attached_disks: true

fileserver_attached_disks:
  # 10 GB test disk for docker compose proxy volume
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
    partition_label: 10-GB-VD-0
    mount_point: "/home/{{ default_user }}/docker_mounts/proxy"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted
  # 10 GB test disk for docker mounts montoring volume
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi2
    partition_label: 10-GB-VD-1
    mount_point: "/home/{{ default_user }}/docker_mounts/monitoring"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted
