# tailscale host variables for docker-testing.home.stechsolutions.ca host

# tailscale
tailscale_setup: true
tailscale_authkey: "{{ secret_ts_client_secret }}?ephemeral=false&preauthorized=true"
tailscale_args: "--advertise-tags='tag:server'"
