{
 "title": "Docker CAdvisor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(cadvisor_version_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(cadvisor_version_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_last_seen{instance=~\"$node\", job=\"$job\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"$node\", job=~\"$job\", name=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=~\"$node\", job=~\"$job\", name=~\"$container\"}) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{instance=~\"$node\", job=~\"$job\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{instance=~\"$node\", job=~\"$job\", name=~\"$container\"}[$__interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{instance=~\"$node\", job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{instance=~\"$node\", job=~\"$job\", name=~\"$container\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(name) (container_memory_usage_bytes{instance=~\"$node\", job=~\"$job\", name=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_network_receive_bytes_total{job=\"$job\", instance=~\"$node\", name=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "recv {{name}}"
    },
    {
     "expr": "-sum by(name) (rate(container_network_transmit_bytes_total{job=\"$job\", instance=~\"$node\", name=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "trans {{name}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_fs_reads_bytes_total{job=\"$job\", instance=~\"$node\", name=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "read {{name}}"
    },
    {
     "expr": "-sum by(name) (rate(container_fs_writes_bytes_total{job=\"$job\", instance=~\"$node\", name=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "write {{name}}"
    }
   ]
  }
 ]
}