{
 "title": "File Storage",
 "tags": [ "ZFS" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "disdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "Data Written and Read",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(node_zfs_zpool_dataset_nwritten{job=\"node\", instance=\"storage.home.stechsolutions.ca:9100\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(node_zfs_zpool_dataset_nread{job=\"node\", instance=\"storage.home.stechsolutions.ca:9100\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "All Filesystems",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n      (1 - node_filesystem_avail_bytes{job=\"$job\", instance=\"$node\", fstype!~\"tmpfs|overlay|squashfs|nfs|nfs4|fuse|fuse.lxcfs\",\r\n  mountpoint!~\".+\\\\.zfs.+|/boot.*|/export.*\"} /\r\n    node_filesystem_size_bytes{job=\"$job\", instance=\"$node\", fstype!~\"tmpfs|overlay|squashfs|nfs|nfs4|fuse|fuse.lxcfs\",\r\n  mountpoint!~\".+\\\\.zfs.+|/boot.*|/export.*\"}) * 100\r\n    ) > 0.01",
     "legendFormat": "{{mountpoint}} ({{fstype}})"
    }
   ]
  },
  {
   "title": "File System Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"$job\", instance=\"$node\", fstype!~\"tmpfs|overlay|squashfs|nfs|nfs4|fuse|fuse.lxcfs\", mountpoint!~\".+\\\\.zfs.+|/boot.*|/export.*\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"$job\", instance=\"$node\", fstype!~\"tmpfs|overlay|squashfs|nfs|nfs4|fuse|fuse.lxcfs\", mountpoint!~\".+\\\\.zfs.+|/boot.*|/export.*\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Zpool Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": " zpool_size_bytes{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "{{pool}} (Total)"
    },
    {
     "expr": "zpool_allocated_bytes{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "{{pool}} (Allocated)"
    },
    {
     "expr": "zpool_free_bytes{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "{{pool}} (Free)"
    }
   ]
  },
  {
   "title": "Zpool Capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zpool_capacity_percent{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Zpool Fragmentation",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zpool_fragmentation_percent{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "ZFS Dataset I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": " rate(node_zfs_zpool_dataset_nread{job=\"$job\", instance=\"$node\"}[5m])",
     "legendFormat": "{{dataset}} read"
    },
    {
     "expr": "-rate(node_zfs_zpool_dataset_nwritten{job=\"$job\", instance=\"$node\"}[5m])",
     "legendFormat": "{{dataset}} write"
    }
   ]
  },
  {
   "title": "Ext4 I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"$job\", instance=\"$node\", device!~\"loop.*|dm-.*|sr.*\"}[5m])\r\n    * on(instance, device) group_left(mountpoint)\r\n    label_replace(\r\n      node_filesystem_free_bytes{job=\"$job\", instance=\"$node\", fstype!~\"tmpfs|overlay|squashfs|nfs|nfs4|fuse|fuse.lxcfs|zfs|ramfs\",\r\n  mountpoint!~\".+\\\\.zfs.+|/boot.*|/export.*\"} ^ 0,\r\n      \"device\", \"$1\", \"device\", \"/dev/([a-z]+(?:[0-9]+n[0-9]+)?)p?[0-9]*\"\r\n    )",
     "legendFormat": "{{mountpoint}} read"
    },
    {
     "expr": "-rate(node_disk_written_bytes_total{job=\"$job\", instance=\"$node\", device!~\"loop.*|dm-.*|sr.*\"}[5m])\r\n    * on(instance, device) group_left(mountpoint)\r\n    label_replace(\r\n      node_filesystem_free_bytes{job=\"$job\", instance=\"$node\", fstype!~\"tmpfs|overlay|squashfs|nfs|nfs4|fuse|fuse.lxcfs|zfs|ramfs\",\r\n  mountpoint!~\".+\\\\.zfs.+|/boot.*|/export.*\"} ^ 0,\r\n      \"device\", \"$1\", \"device\", \"/dev/([a-z]+(?:[0-9]+n[0-9]+)?)p?[0-9]*\"\r\n    )",
     "legendFormat": "{{mountpoint}} write"
    }
   ]
  },
  { "title": "Time Until Projected Full", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "ZFS Datasets",
   "type": "stat",
   "description": "ZFS datasets that are filling up",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n    node_filesystem_free_bytes{job=\"$job\", instance=\"$node\", fstype=\"zfs\", mountpoint!~\".+\\\\.zfs.+|/export.*\"}\r\n    /\r\n    -deriv(node_filesystem_free_bytes{job=\"$job\", instance=\"$node\", fstype=\"zfs\", mountpoint!~\".+\\\\.zfs.+|/export.*\"}[1d])\r\n  ) / 86400 > 0 < 365",
     "legendFormat": "{{mountpoint}} (filesystem)"
    }
   ]
  },
  {
   "title": "Ext4",
   "type": "stat",
   "description": "Ext4 filesystems that are filling up",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n    node_filesystem_free_bytes{job=\"$job\", instance=\"$node\", fstype!~\"tmpfs|overlay|squashfs|nfs|nfs4|fuse|fuse.lxcfs|zfs|ramfs\",\r\n  mountpoint!~\".+\\\\.zfs.+|/boot.*|/export.*\"}\r\n    /\r\n    -deriv(node_filesystem_free_bytes{job=\"$job\", instance=\"$node\", fstype!~\"tmpfs|overlay|squashfs|nfs|nfs4|fuse|fuse.lxcfs|zfs|ramfs\",\r\n  mountpoint!~\".+\\\\.zfs.+|/boot.*|/export.*\"}[1d])\r\n  ) / 86400 > 0 < 365",
     "legendFormat": "{{mountpoint}} (filesystem)"
    }
   ]
  },
  {
   "title": "ZFS Pools",
   "type": "stat",
   "description": "ZFS pools that are filling up",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n    zpool_free_bytes{job=\"$job\", instance=\"$node\"}\r\n    /\r\n    -deriv(zpool_free_bytes{job=\"$job\", instance=\"$node\"}[1d])\r\n  ) / 86400 > 0 < 365",
     "legendFormat": "{{pool}} (pool)"
    }
   ]
  },
  { "title": "Sanoid and Syncoid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Snapshot Recent Ages",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "zfs_snapshot_type_age_seconds{job=\"$job\", instance=\"$node\"} / 3600",
     "legendFormat": "{{dataset}}"
    }
   ]
  },
  {
   "title": "Snapshot Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "zfs_snapshot_type_count{job=\"$job\", instance=\"$node\"}",
     "legendFormat": "{{dataset}}"
    }
   ]
  }
 ]
}