{
 "title": "Proxmox Backup Server",
 "tags": [ "proxmox" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "query": { "query": "label_values(pbs_up,instance)" } },
   {
    "name": "datastore",
    "label": "Datasource",
    "query": {
     "query": "label_values(pbs_size,datastore)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(pbs_snapshot_count{datastore=~\"$datastore\"},namespace)"
    }
   },
   {
    "name": "vmname",
    "label": "VM Name",
    "query": {
     "query": "label_values(pbs_snapshot_vm_count{namespace=~\"$namespace\",datastore=~\"$datastore\"},vm_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbs_host_uptime{job=\"pbs\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Snapshot overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "pbs_snapshot_vm_last_timestamp{job=\"pbs\", instance=\"$instance\", namespace=~\"$namespace\", datastore=~\"$datastore\", vm_name=~\"$vmname\"} * 1000"
    },
    {
     "expr": "pbs_snapshot_vm_last_verify{job=\"pbs\", instance=\"$instance\", namespace=~\"$namespace\", datastore=~\"$datastore\", vm_name=~\"$vmname\"}"
    }
   ]
  },
  {
   "title": "Total Snapshots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pbs_snapshot_count{job=\"pbs\", instance=\"$instance\"})"
    }
   ]
  },
  { "title": "Snapshots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Snapshots by Namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "pbs_snapshot_count{job=\"pbs\", instance=\"$instance\", datastore=~\"$datastore\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Snapshot count by VM",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "pbs_snapshot_vm_count{job=\"pbs\", instance=\"$instance\", datastore=~\"$datastore\", namespace=~\"$namespace\", vm_name=~\"$vmname\"}"
    }
   ]
  },
  { "title": "Datastore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Datastore Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pbs_available{job=\"pbs\", instance=\"$instance\", datastore=~\"$datastore\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pbs_size{job=\"pbs\", instance=\"$instance\", datastore=~\"$datastore\"}"
    },
    {
     "expr": "pbs_used{job=\"pbs\", instance=\"$instance\", datastore=~\"$datastore\"}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pbs_host_cpu_usage{job=\"pbs\",instance=\"$instance\"}",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "pbs_host_load1{job=\"pbs\",instance=\"$instance\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "pbs_host_load5{job=\"pbs\",instance=\"$instance\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "pbs_host_load15{job=\"pbs\",instance=\"$instance\"}",
     "legendFormat": "15m load average"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pbs_host_memory_used{job=\"pbs\", instance=\"$instance\"}",
     "legendFormat": "memory used"
    },
    {
     "expr": "pbs_host_memory_free{job=\"pbs\", instance=\"$instance\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbs_host_memory_used{job=\"pbs\", instance=\"$instance\"} / pbs_host_memory_total{job=\"pbs\", instance=\"$instance\"} * 100"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pbs_host_swap_used{job=\"pbs\", instance=\"$instance\"}",
     "legendFormat": "swap used"
    },
    {
     "expr": "pbs_host_swap_free{job=\"pbs\", instance=\"$instance\"}",
     "legendFormat": "swap free"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbs_host_swap_used{job=\"pbs\", instance=\"$instance\"} / pbs_host_swap_total{job=\"pbs\", instance=\"$instance\"} * 100"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Disk I/O Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pbs_host_io_wait{instance=\"$instance\"}",
     "legendFormat": "io delay"
    }
   ]
  },
  {
   "title": "Root Disk Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pbs_host_disk_total{job=\"pbs\", instance=\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "pbs_host_disk_used{job=\"pbs\", instance=\"$instance\"}",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Root Disk Space Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbs_host_disk_used{job=\"pbs\", instance=\"$instance\"} / pbs_host_disk_total{job=\"pbs\",instance=\"$instance\"} * 100"
    }
   ]
  }
 ]
}