{
 "title": "Pi-hole Exporter",
 "description": "This is a Pi-hole dashboard when using the https://github.com/eko/pihole-exporter Prometheus exporter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(pihole_status,job)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(pihole_status{job=\"$job\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "🥧🕳️ Pi-hole", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_status{hostname=~\"$node\", job=\"$job\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pihole_domains_being_blocked{hostname=~\"$node\", job=\"$job\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Unique domains",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pihole_unique_domains{hostname=~\"$node\", job=\"$job\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Top queries by domain",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(domain) (pihole_top_queries{hostname=~\"$node\", job=\"$job\"})",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Replies by type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (pihole_reply{hostname=~\"$node\", job=\"$job\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(domain) (pihole_top_ads{hostname=~\"$node\", job=\"$job\"})",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "DNS queries all of types",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pihole_dns_queries_all_types{hostname=~\"$node\", job=\"$job\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "% ads blocked",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(job) (pihole_ads_percentage_today{hostname=~\"$node\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Ads blocked (today)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pihole_ads_blocked_today{hostname=~\"$node\", job=\"$job\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Queries cached/forwarded",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job) (pihole_queries_cached{hostname=~\"$node\", job=\"$job\"})",
     "legendFormat": "Queries cached"
    },
    {
     "expr": "sum by(job) (pihole_queries_forwarded{hostname=~\"$node\", job=\"$job\"})",
     "legendFormat": "Queries forwarded"
    }
   ]
  },
  {
   "title": "DNS Query types",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(type) (pihole_querytypes)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "pihole_ads_percentage_today", "legendFormat": "{{ hostname }}" }
   ]
  },
  {
   "title": "Top queries",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "topk(15, sum by(domain) (pihole_top_queries))",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Top ads domains",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(domain) (topk(15, pihole_top_ads))",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Forward destinations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(destination) (pihole_forward_destinations{hostname=~\"$node\"})",
     "legendFormat": "{{ destination }}"
    }
   ]
  },
  {
   "title": "Unique clients",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pihole_unique_clients{hostname=~\"$node\", job=\"$job\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Top sources",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(source) (topk(15, pihole_top_sources))",
     "legendFormat": "{{ domain }}"
    }
   ]
  }
 ]
}