{
 "title": "Tailscale / Overview",
 "description": "A dashboard that gives an overview of Tailscale API metrics. The dashboards were generated using [tailscale-mixin](https://github.com/adinhodovic/tailscale-exporter/tree/main/tailscale-mixin). Open issues and create feature requests in the repository.",
 "tags": [ "Tailscale" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(tailscale_up,job)" } },
   {
    "name": "tailnet",
    "label": "Tailnet",
    "query": {
     "query": "label_values(tailscale_up{job=\"$job\"},tailnet)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users",
   "type": "stat",
   "description": "The total number of users in the selected tailnet.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tailscale_users_info{job=\"$job\", tailnet=\"$tailnet\"})"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "stat",
   "description": "The total number of devices in the selected tailnet.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tailscale_devices_info{job=\"$job\", tailnet=\"$tailnet\"})"
    }
   ]
  },
  {
   "title": "Devices Logged In",
   "type": "stat",
   "description": "The total number of devices that are currently online in the selected tailnet.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tailscale_devices_online{job=\"$job\", tailnet=\"$tailnet\"})"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "stat",
   "description": "The total number of keys in the selected tailnet.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tailscale_keys_info{job=\"$job\", tailnet=\"$tailnet\"})"
    }
   ]
  },
  {
   "title": "Nameservers",
   "type": "table",
   "description": "A table showing the nameservers configured for the selected tailnet.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by(nameserver) (tailscale_dns_nameservers_info{job=\"$job\", tailnet=\"$tailnet\"})"
    }
   ]
  },
  {
   "title": "Magic DNS Enabled",
   "type": "stat",
   "description": "Whether Magic DNS is enabled for the selected tailnet.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tailscale_dns_magic_dns{job=\"$job\", tailnet=\"$tailnet\"})"
    }
   ]
  },
  {
   "title": "Tailnet Settings",
   "type": "table",
   "description": "A table showing the current settings for the selected tailnet.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "tailscale_tailnet_settings_info{job=\"$job\", tailnet=\"$tailnet\"}"
    }
   ]
  },
  { "title": "Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Devices by OS",
   "type": "piechart",
   "description": "A pie chart showing the distribution of devices by operating system in the selected tailnet.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(os) (tailscale_devices_info{job=\"$job\", tailnet=\"$tailnet\"})",
     "legendFormat": "{{ os }}"
    }
   ]
  },
  {
   "title": "Devices by Version",
   "type": "piechart",
   "description": "A pie chart showing the distribution of devices by Tailscale client version in the selected tailnet.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(client_version) (tailscale_devices_info{job=\"$job\", tailnet=\"$tailnet\"})",
     "legendFormat": "{{ client_version }}"
    }
   ]
  },
  {
   "title": "Devices with Update Available",
   "type": "piechart",
   "description": "The total number of devices that have an update available in the selected tailnet.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(tailscale_devices_update_available{job=\"$job\", tailnet=\"$tailnet\"} == 1)",
     "legendFormat": "Update Available"
    },
    {
     "expr": "count(tailscale_devices_update_available{job=\"$job\", tailnet=\"$tailnet\"} == 0)",
     "legendFormat": "No Update Available"
    }
   ]
  },
  {
   "title": "Authorized Devices",
   "type": "piechart",
   "description": "The total number of devices that are authorized to access the tailnet.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(tailscale_devices_authorized{job=\"$job\", tailnet=\"$tailnet\"} == 1)",
     "legendFormat": "Authorized"
    },
    {
     "expr": "count(tailscale_devices_authorized{job=\"$job\", tailnet=\"$tailnet\"} == 0)",
     "legendFormat": "Not Authorized"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "description": "A table showing all devices in the selected tailnet.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "tailscale_devices_info{job=\"$job\", tailnet=\"$tailnet\"}"
    }
   ]
  },
  {
   "title": "Devices Settings",
   "type": "table",
   "description": "A table showing all devices in the selected tailnet.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "min by(name, id) (tailscale_devices_created_timestamp{job=\"$job\", tailnet=\"$tailnet\"} * 1000)"
    },
    {
     "expr": "min(\n  tailscale_devices_expires_timestamp{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } * 1000\n) by (name, id)\n"
    },
    {
     "expr": "sum(\n  tailscale_devices_authorized{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n"
    },
    {
     "expr": "sum(\n  tailscale_devices_blocks_incoming{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n"
    },
    {
     "expr": "sum(\n  tailscale_devices_routes_enabled{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n"
    },
    {
     "expr": "sum(\n  tailscale_devices_routes_advertised{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n"
    },
    {
     "expr": "sum(\n  tailscale_devices_key_expiry_disabled{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n"
    },
    {
     "expr": "sum(\n  tailscale_devices_external{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  }\n) by (name, id)\n"
    }
   ]
  },
  {
   "title": "Update Available",
   "type": "timeseries",
   "description": "A timeseries panel showing devices that have an update available.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "sum by(name, id) (tailscale_devices_update_available{job=\"$job\", tailnet=\"$tailnet\"}) == 1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Time Since Last Seen",
   "type": "timeseries",
   "description": "A timeseries panel showing the last time a device was seen.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - (max by(name, id, client_version) (tailscale_devices_last_seen_timestamp{job=\"$job\", tailnet=\"$tailnet\"}))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Users by Role",
   "type": "piechart",
   "description": "A pie chart showing the distribution of users by role in the selected tailnet.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(role) (tailscale_users_info{job=\"$job\", tailnet=\"$tailnet\"})",
     "legendFormat": "{{ role }}"
    }
   ]
  },
  {
   "title": "Users by Status",
   "type": "piechart",
   "description": "A pie chart showing the distribution of users by status in the selected tailnet.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(status) (tailscale_users_info{job=\"$job\", tailnet=\"$tailnet\"})",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Users by Type",
   "type": "piechart",
   "description": "A pie chart showing the distribution of users by type in the selected tailnet.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(type) (tailscale_users_info{job=\"$job\", tailnet=\"$tailnet\"})",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Users Logged In",
   "type": "piechart",
   "description": "The total number of users that are currently logged in to the selected tailnet.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(tailscale_users_currently_logged_in{job=\"$job\", tailnet=\"$tailnet\"} == 1)",
     "legendFormat": "Logged In"
    },
    {
     "expr": "count(\n  tailscale_users_currently_logged_in{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } == 0\n)\n",
     "legendFormat": "Logged Out"
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "description": "A table showing all users in the selected tailnet.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tailscale_users_info{job=\"$job\", tailnet=\"$tailnet\"}"
    },
    {
     "expr": "min(\n  tailscale_users_created_timestamp{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } * 1000\n) by (name, id)\n"
    },
    {
     "expr": "max(\n  tailscale_users_last_seen_timestamp{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } * 1000\n) by (name, id)\n"
    }
   ]
  },
  { "title": "Keys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Keys",
   "type": "table",
   "description": "A table showing all keys in the selected tailnet.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "tailscale_keys_info{job=\"$job\", tailnet=\"$tailnet\"}"
    },
    {
     "expr": "min(\n  tailscale_keys_created_timestamp{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } * 1000\n) by (name, id, key_type, user_id)\n"
    },
    {
     "expr": "min(\n  tailscale_keys_expires_timestamp{\n    cluster=\"$cluster\"\n,\nnamespace=\"$namespace\",\njob=\"$job\",\ntailnet=\"$tailnet\"\n\n  } * 1000\n) by (name, id, key_type, user_id)\n"
    }
   ]
  }
 ]
}