{
 "title": "Tailscale / Machine",
 "description": "A dashboard that gives an overview of Tailscale Machine daemon metrics. ",
 "tags": [ "Tailscale" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(tailscaled_health_messages,job)"
    }
   },
   {
    "name": "tailscale_machine",
    "label": "Tailscale Machine",
    "query": {
     "query": "label_values(tailscaled_health_messages{job=~\"$job\"},tailscale_machine)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tailscale Machines",
   "type": "stat",
   "description": "A stat panel showing the number of Tailscale machines reporting to the selected Tailscale control plane.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(tailscaled_health_messages{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Advertised / Approved Routes",
   "type": "piechart",
   "description": "A pie chart panel showing the number of advertised and approved routes for the selected Tailscale machines.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tailscaled_advertised_routes{job=~\"$job\"})",
     "legendFormat": "Advertised"
    },
    {
     "expr": "sum(tailscaled_approved_routes{job=~\"$job\"})",
     "legendFormat": "Approved"
    }
   ]
  },
  {
   "title": "Paths Distribution Inbound [1h]",
   "type": "piechart",
   "description": "A pie chart panel showing the distribution of outbound paths for the selected Tailscale machines.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(path) (increase(tailscaled_inbound_bytes_total{job=~\"$job\"}[1h]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Paths Distribution Outbound [1h]",
   "type": "piechart",
   "description": "A pie chart panel showing the distribution of inbound paths for the selected Tailscale machines.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(path) (increase(tailscaled_outbound_bytes_total{job=~\"$job\"}[1h]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Inbound vs Outbound Traffic [1h]",
   "type": "piechart",
   "description": "A pie chart panel showing the distribution of outbound paths for the selected Tailscale machines.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(tailscaled_inbound_bytes_total{job=~\"$job\"}[1h]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(tailscaled_outbound_bytes_total{job=~\"$job\"}[1h]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Dropped Packets by Reason [1h]",
   "type": "piechart",
   "description": "A pie chart panel showing the distribution of dropped packets by reason for the selected Tailscale machines.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (increase(tailscaled_outbound_dropped_packets_total{job=~\"$job\"}[1h]))",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Top 20 Machines by Inbound Traffic (1h)",
   "type": "table",
   "description": "A table panel showing the top 20 Tailscale machines by inbound traffic over the last hour.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(20, sum by(tailscale_machine) (rate(tailscaled_inbound_bytes_total{job=~\"$job\"}[1h])))"
    }
   ]
  },
  {
   "title": "Machines with Unapproved Routes",
   "type": "table",
   "description": "A table panel showing the Tailscale machines with unadvertised routes.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum by(tailscale_machine) (tailscaled_advertised_routes{job=~\"$job\"}) > 0) - (sum by(tailscale_machine) (tailscaled_approved_routes{job=~\"$job\"}))"
    }
   ]
  },
  {
   "title": "Machines with Dropped Packets (1h)",
   "type": "table",
   "description": "A table panel showing the Tailscale machines with dropped packets in the last hour.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(tailscale_machine) (increase(tailscaled_outbound_dropped_packets_total{job=~\"$job\"}[1h])) * 100 > 0) / (sum by(tailscale_machine) (increase(tailscaled_outbound_packets_total{job=~\"$job\"}[1h])))"
    }
   ]
  },
  { "title": "Network Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Health Messages by Type",
   "type": "timeseries",
   "description": "A bar gauge panel showing the number of health messages by type.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(type) (tailscaled_health_messages{job=~\"$job\"})",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Outbound Dropped Packets by Reason",
   "type": "timeseries",
   "description": "A timeseries panel showing the outbound dropped packets by reason.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(reason) (increase(tailscaled_outbound_dropped_packets_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Inbound Bytes by Path",
   "type": "timeseries",
   "description": "A timeseries panel showing the inbound bytes by path.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(path) (increase(tailscaled_inbound_bytes_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Inbound Packets by Path",
   "type": "timeseries",
   "description": "A timeseries panel showing the inbound packets by path.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(path) (increase(tailscaled_inbound_packets_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Outbound Bytes by Path",
   "type": "timeseries",
   "description": "A timeseries panel showing the outbound bytes by path.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(path) (increase(tailscaled_outbound_bytes_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Outbound Packets by Path",
   "type": "timeseries",
   "description": "A timeseries panel showing the outbound packets by path.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(path) (increase(tailscaled_outbound_packets_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Tailscale Machine $tailscale_machine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "tailscale_machine"
  },
  {
   "title": "Advertised / Approved Routes",
   "type": "piechart",
   "description": "A pie chart panel showing the number of advertised and approved routes for the selected Tailscale machines.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tailscaled_advertised_routes{job=~\"$job\", tailscale_machine=\"$tailscale_machine\"})",
     "legendFormat": "Advertised"
    },
    {
     "expr": "sum(tailscaled_approved_routes{job=~\"$job\", tailscale_machine=\"$tailscale_machine\"})",
     "legendFormat": "Approved"
    }
   ]
  },
  {
   "title": "DERP vs Non-DERP Outbound Traffic [1h]",
   "type": "piechart",
   "description": "A pie chart panel showing the DERP vs Non-DERP outbound traffic for the selected Tailscale machine.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(tailscaled_outbound_bytes_total{job=~\"$job\", tailscale_machine=\"$tailscale_machine\", path=\"derp\"}[1h]))",
     "legendFormat": "DERP"
    },
    {
     "expr": "sum(rate(tailscaled_outbound_bytes_total{job=~\"$job\", tailscale_machine=\"$tailscale_machine\", path!=\"derp\"}[1h]))",
     "legendFormat": "Non-DERP"
    }
   ]
  },
  {
   "title": "Dropped Packets by Reason [1h]",
   "type": "piechart",
   "description": "A pie chart panel showing the distribution of dropped packets by reason for the selected Tailscale machines.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (increase(tailscaled_outbound_dropped_packets_total{job=~\"$job\", tailscale_machine=\"$tailscale_machine\"}[1h]))",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Health Messages by Type",
   "type": "timeseries",
   "description": "A bar gauge panel showing the number of health messages by type for the selected Tailscale machine.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(type) (tailscaled_health_messages{job=~\"$job\", tailscale_machine=\"$tailscale_machine\"})",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Outbound Dropped Packets by Reason",
   "type": "timeseries",
   "description": "A timeseries panel showing the outbound dropped packets by reason for the selected Tailscale machine.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(reason) (increase(tailscaled_outbound_dropped_packets_total{job=~\"$job\", tailscale_machine=\"$tailscale_machine\"}[$__rate_interval]))",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Inbound Bytes by Path",
   "type": "timeseries",
   "description": "A timeseries panel showing the inbound bytes by path for the selected Tailscale machine.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(path) (increase(tailscaled_inbound_bytes_total{job=~\"$job\", tailscale_machine=\"$tailscale_machine\"}[$__rate_interval]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Inbound Packets by Path",
   "type": "timeseries",
   "description": "A timeseries panel showing the inbound packets by path for the selected Tailscale machine.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(path) (increase(tailscaled_inbound_packets_total{job=~\"$job\", tailscale_machine=\"$tailscale_machine\"}[$__rate_interval]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Outbound Bytes by Path",
   "type": "timeseries",
   "description": "A timeseries panel showing the outbound bytes by path for the selected Tailscale machine.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(path) (increase(tailscaled_outbound_bytes_total{job=~\"$job\", tailscale_machine=\"$tailscale_machine\"}[$__rate_interval]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Outbound Packets by Path",
   "type": "timeseries",
   "description": "A timeseries panel showing the outbound packets by path for the selected Tailscale machine.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(path) (increase(tailscaled_outbound_packets_total{job=~\"$job\", tailscale_machine=\"$tailscale_machine\"}[$__rate_interval]))",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}