{
 "title": "Node - ZFS Stats",
 "description": "ZFS metrics as extracted by node_exporter",
 "tags": [
  "OS",
  "ZFS",
  "Prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Prometheus_server", "label": "Prometheus_server", "query": "prometheus" },
   {
    "name": "Host",
    "label": "Host",
    "query": "label_values(node_zfs_arc_c, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Arc Percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_arc_c{instance=~\"$Host\"} / node_zfs_arc_c_max{instance=~\"$Host\"} * 100"
    }
   ]
  },
  {
   "title": "Arc Value",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_arc_c{instance=~\"$Host\"}"
    }
   ]
  },
  { "title": "Arc Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "arc_c",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_c{instance=~\"$Host\"}",
     "legendFormat": "arc current"
    },
    {
     "expr": "node_zfs_arc_c_max{instance=~\"$Host\"}",
     "legendFormat": "arc_max"
    },
    {
     "expr": "node_zfs_arc_c_min{instance=~\"$Host\"}",
     "legendFormat": "arc_min"
    }
   ]
  },
  {
   "title": "arc_size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_size{instance=~\"$Host\"}",
     "legendFormat": "arc_size"
    }
   ]
  },
  {
   "title": "arc_anon",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_anon_evictable_data{instance=~\"$Host\"}",
     "legendFormat": "evictable_data"
    },
    {
     "expr": "node_zfs_arc_anon_evictable_metadata{instance=~\"$Host\"}",
     "legendFormat": "evictable_metadata"
    },
    {
     "expr": "node_zfs_arc_anon_size{instance=~\"$Host\"}",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "arc_arc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_arc_loaned_bytes{instance=~\"$Host\"}",
     "legendFormat": "loaned_bytes"
    },
    {
     "expr": "node_zfs_arc_arc_meta_limit{instance=~\"$Host\"}",
     "legendFormat": "meta_limit"
    },
    {
     "expr": "node_zfs_arc_arc_meta_max{instance=~\"$Host\"}",
     "legendFormat": "meta_max"
    },
    {
     "expr": "node_zfs_arc_arc_meta_min{instance=~\"$Host\"}",
     "legendFormat": "meta_min"
    },
    {
     "expr": "node_zfs_arc_arc_meta_used{instance=~\"$Host\"}",
     "legendFormat": "meta_used"
    },
    {
     "expr": "node_zfs_arc_arc_need_free{instance=~\"$Host\"}",
     "legendFormat": "need_free"
    },
    {
     "expr": "node_zfs_arc_arc_no_grow{instance=~\"$Host\"}",
     "legendFormat": "no_grow"
    },
    {
     "expr": "node_zfs_arc_arc_prune{instance=~\"$Host\"}",
     "legendFormat": "prune"
    },
    {
     "expr": "node_zfs_arc_arc_sys_free{instance=~\"$Host\"}",
     "legendFormat": "sys_free"
    },
    {
     "expr": "node_zfs_arc_arc_tempreserve{instance=~\"$Host\"}",
     "legendFormat": "tempreserve"
    }
   ]
  },
  {
   "title": "arc_data_size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_data_size{instance=~\"$Host\"}",
     "legendFormat": "arc_data_size"
    }
   ]
  },
  {
   "title": "arc_deleted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_deleted{instance=~\"$Host\"}",
     "legendFormat": "arc_deleted"
    }
   ]
  },
  {
   "title": "arc_demand",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_demand_data_hits{instance=~\"$Host\"}[5m])",
     "legendFormat": "data_hits"
    },
    {
     "expr": "rate(node_zfs_arc_demand_data_misses{instance=~\"$Host\"}[5m])",
     "legendFormat": "data_misses"
    },
    {
     "expr": "rate(node_zfs_arc_demand_metadata_hits{instance=~\"$Host\"}[5m])",
     "legendFormat": "metadata_hits"
    },
    {
     "expr": "rate(node_zfs_arc_demand_metadata_misses{instance=~\"$Host\"}[5m])",
     "legendFormat": "metadata_misses"
    },
    {
     "expr": "rate(node_zfs_arc_demand_data_hits{instance=~\"$Host\"}[5m]) / (rate(node_zfs_arc_demand_data_hits{instance=~\"$Host\"}[5m]) +\r\n  rate(node_zfs_arc_demand_data_iohits{instance=~\"$Host\"}[5m]) + rate(node_zfs_arc_demand_data_misses{instance=~\"$Host\"}[5m])) * 100",
     "legendFormat": "data_hits percentage"
    },
    {
     "expr": "rate(node_zfs_arc_demand_metadata_hits{instance=~\"$Host\"}[5m]) / (rate(node_zfs_arc_demand_metadata_hits{instance=~\"$Host\"}[5m]) + rate(node_zfs_arc_demand_metadata_misses{instance=~\"$Host\"}[5m])) * 100",
     "legendFormat": "metadata_hits percentage"
    }
   ]
  },
  {
   "title": "arc_evict",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_evict_l2_cached{instance=~\"$Host\"}",
     "legendFormat": "l2_cached"
    },
    {
     "expr": "node_zfs_arc_evict_l2_eligible{instance=~\"$Host\"}",
     "legendFormat": "l2_eligible"
    },
    {
     "expr": "node_zfs_arc_evict_l2_ineligible{instance=~\"$Host\"}",
     "legendFormat": "l2_ineligible"
    },
    {
     "expr": "node_zfs_arc_evict_l2_skip{instance=~\"$Host\"}",
     "legendFormat": "l2_skip"
    },
    {
     "expr": "node_zfs_arc_evict_not_enough{instance=~\"$Host\"}",
     "legendFormat": "not_enough"
    },
    {
     "expr": "node_zfs_arc_evict_skip{instance=~\"$Host\"}",
     "legendFormat": "skip"
    }
   ]
  },
  {
   "title": "arc_hash",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_zfs_arc_hash_chain_max{instance=~\"$Host\"}",
     "legendFormat": "chain_max"
    },
    {
     "expr": "node_zfs_arc_hash_chains{instance=~\"$Host\"}",
     "legendFormat": "chains"
    },
    {
     "expr": "node_zfs_arc_hash_elements{instance=~\"$Host\"}",
     "legendFormat": "elements"
    },
    {
     "expr": "node_zfs_arc_hash_elements_max{instance=~\"$Host\"}",
     "legendFormat": "elements_max"
    }
   ]
  },
  {
   "title": "arc_hash_collisions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_hash_collisions{instance=~\"$Host\"}[5m])",
     "legendFormat": "collisions"
    }
   ]
  },
  {
   "title": "arc_hdr_size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_hdr_size{instance=~\"$Host\"}",
     "legendFormat": "hdr_size"
    }
   ]
  },
  {
   "title": "arc_hits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_hits{instance=~\"$Host\"}[5m])",
     "legendFormat": "arc_hits"
    }
   ]
  },
  {
   "title": "arc_l2 - 1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_zfs_arc_l2_abort_lowmem{instance=~\"$Host\"}",
     "legendFormat": "abort_lowmem"
    },
    {
     "expr": "node_zfs_arc_l2_asize{instance=~\"$Host\"}",
     "legendFormat": "asize"
    },
    {
     "expr": "node_zfs_arc_l2_cdata_free_on_write{instance=~\"$Host\"}",
     "legendFormat": "cdata_free_on_write"
    },
    {
     "expr": "node_zfs_arc_l2_cksum_bad{instance=~\"$Host\"}",
     "legendFormat": "cksum_bad"
    },
    {
     "expr": "node_zfs_arc_l2_compress_failure{instance=~\"$Host\"}",
     "legendFormat": "compress_failure"
    },
    {
     "expr": "node_zfs_arc_l2_compress_successes{instance=~\"$Host\"}",
     "legendFormat": "compress_successes"
    },
    {
     "expr": "node_zfs_arc_l2_compress_zeros{instance=~\"$Host\"}",
     "legendFormat": "compress_zeros"
    }
   ]
  },
  {
   "title": "arc_l2 - 2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_zfs_arc_l2_evict_l1cached{instance=~\"$Host\"}",
     "legendFormat": "evict_l1cached"
    },
    {
     "expr": "node_zfs_arc_l2_evict_lock_retry{instance=~\"$Host\"}",
     "legendFormat": "evict_lock_retry"
    },
    {
     "expr": "node_zfs_arc_l2_evict_reading{instance=~\"$Host\"}",
     "legendFormat": "evict_reading"
    },
    {
     "expr": "node_zfs_arc_l2_feeds{instance=~\"$Host\"}",
     "legendFormat": "feeds"
    },
    {
     "expr": "node_zfs_arc_l2_free_on_write{instance=~\"$Host\"}",
     "legendFormat": "free_on_write"
    },
    {
     "expr": "node_zfs_arc_l2_hdr_size{instance=~\"$Host\"}",
     "legendFormat": "hdr_size"
    },
    {
     "expr": "node_zfs_arc_l2_hits{instance=~\"$Host\"}",
     "legendFormat": "hits"
    },
    {
     "expr": "node_zfs_arc_l2_io_error{instance=~\"$Host\"}",
     "legendFormat": "io_error"
    },
    {
     "expr": "node_zfs_arc_l2_misses{instance=~\"$Host\"}",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "arc_l2 - 3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_zfs_arc_l2_read_bytes{instance=~\"$Host\"}",
     "legendFormat": "read_bytes"
    },
    {
     "expr": "node_zfs_arc_l2_rw_clash{instance=~\"$Host\"}",
     "legendFormat": "rw_clash"
    },
    {
     "expr": "node_zfs_arc_l2_size{instance=~\"$Host\"}",
     "legendFormat": "size"
    },
    {
     "expr": "node_zfs_arc_l2_write_bytes{instance=~\"$Host\"}",
     "legendFormat": "write_bytes"
    },
    {
     "expr": "node_zfs_arc_l2_writes_done{instance=~\"$Host\"}",
     "legendFormat": "writes_done"
    },
    {
     "expr": "node_zfs_arc_l2_writes_error{instance=~\"$Host\"}",
     "legendFormat": "writes_error"
    },
    {
     "expr": "node_zfs_arc_l2_writes_lock_retry{instance=~\"$Host\"}",
     "legendFormat": "writes_lock_retry"
    },
    {
     "expr": "node_zfs_arc_l2_writes_sent{instance=~\"$Host\"}",
     "legendFormat": "writes_sent"
    }
   ]
  },
  {
   "title": "arc_memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_memory_direct_count{instance=~\"$Host\"}",
     "legendFormat": "direct_count"
    },
    {
     "expr": "node_zfs_arc_memory_indirect_count{instance=~\"$Host\"}",
     "legendFormat": "indirect_count"
    },
    {
     "expr": "node_zfs_arc_memory_throttle_count{instance=~\"$Host\"}",
     "legendFormat": "throttle_count"
    }
   ]
  },
  {
   "title": "arc_metadata_size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_metadata_size{instance=~\"$Host\"}",
     "legendFormat": "arc_metadata_size"
    }
   ]
  },
  {
   "title": "arc_mfu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_mfu_evictable_data{instance=~\"$Host\"}",
     "legendFormat": "evictable_data"
    },
    {
     "expr": "node_zfs_arc_mfu_evictable_metadata{instance=~\"$Host\"}",
     "legendFormat": "evictable_metadata"
    },
    {
     "expr": "node_zfs_arc_mfu_ghost_evictable_data{instance=~\"$Host\"}",
     "legendFormat": "ghost_evictable_data"
    },
    {
     "expr": "node_zfs_arc_mfu_ghost_evictable_metadata{instance=~\"$Host\"}",
     "legendFormat": "ghost_evictable_metadata"
    },
    {
     "expr": "node_zfs_arc_mfu_ghost_size{instance=~\"$Host\"}",
     "legendFormat": "ghost_size"
    },
    {
     "expr": "node_zfs_arc_mfu_size{instance=~\"$Host\"}",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "arc_mfu -2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_mfu_ghost_hits{instance=~\"$Host\"}[5m])",
     "legendFormat": "ghost_hits"
    },
    {
     "expr": "rate(node_zfs_arc_mfu_hits{instance=~\"$Host\"}[5m])",
     "legendFormat": "hits"
    }
   ]
  },
  {
   "title": "arc_misses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_misses{instance=~\"$Host\"}[5m])",
     "legendFormat": "ghost_hits"
    }
   ]
  },
  {
   "title": "arc_mru - 1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_mru_evictable_data{instance=~\"$Host\"}",
     "legendFormat": "evictable_data"
    },
    {
     "expr": "node_zfs_arc_mru_evictable_metadata{instance=~\"$Host\"}",
     "legendFormat": "evictable_metadata"
    },
    {
     "expr": "node_zfs_arc_mru_ghost_evictable_data{instance=~\"$Host\"}",
     "legendFormat": "ghost_evictable_data"
    },
    {
     "expr": "node_zfs_arc_mru_ghost_evictable_metadata{instance=~\"$Host\"}",
     "legendFormat": "ghost_evictable_metadata"
    },
    {
     "expr": "node_zfs_arc_mru_ghost_size{instance=~\"$Host\"}",
     "legendFormat": "ghost_size"
    },
    {
     "expr": "node_zfs_arc_mru_size{instance=~\"$Host\"}",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "arc_mru -2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_mru_ghost_hits{instance=~\"$Host\"}[5m])",
     "legendFormat": "ghost_hits"
    },
    {
     "expr": "rate(node_zfs_arc_mru_hits{instance=~\"$Host\"}[5m])",
     "legendFormat": "hits"
    }
   ]
  },
  {
   "title": "arc_mutex_miss",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_mutex_miss{instance=~\"$Host\"}[5m])",
     "legendFormat": "arc_mutex_miss"
    }
   ]
  },
  {
   "title": "arc_p",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_pd{instance=~\"$Host\"}",
     "legendFormat": "pd"
    },
    {
     "expr": "node_zfs_arc_pm{instance=~\"$Host\"}",
     "legendFormat": "pm"
    }
   ]
  },
  {
   "title": "arc_prefetch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_prefetch_data_hits{instance=~\"$Host\"}[5m])",
     "legendFormat": "data_hits"
    },
    {
     "expr": "rate(node_zfs_arc_prefetch_data_misses{instance=~\"$Host\"}[5m])",
     "legendFormat": "data_misses"
    },
    {
     "expr": "rate(node_zfs_arc_prefetch_metadata_hits{instance=~\"$Host\"}[5m])",
     "legendFormat": "metadata_hits"
    },
    {
     "expr": "rate(node_zfs_arc_prefetch_metadata_misses{instance=~\"$Host\"}[5m])",
     "legendFormat": "metadata_misses"
    },
    {
     "expr": "rate(node_zfs_arc_prefetch_data_hits{instance=~\"$Host\"}[5m]) / (rate(node_zfs_arc_prefetch_data_hits{instance=~\"$Host\"}[5m]) +\r\n  rate(node_zfs_arc_prefetch_data_iohits{instance=~\"$Host\"}[5m]) + rate(node_zfs_arc_prefetch_data_misses{instance=~\"$Host\"}[5m])) * 100",
     "legendFormat": "data_hits percentage"
    },
    {
     "expr": "rate(node_zfs_arc_prefetch_metadata_hits{instance=~\"$Host\"}[5m]) / (rate(node_zfs_arc_prefetch_metadata_hits{instance=~\"$Host\"}[5m]) +\r\n  rate(node_zfs_arc_prefetch_metadata_iohits{instance=~\"$Host\"}[5m]) + rate(node_zfs_arc_prefetch_metadata_misses{instance=~\"$Host\"}[5m])) * 100",
     "legendFormat": "metadata_hits percentage"
    },
    {
     "expr": "rate(node_zfs_arc_prefetch_data_iohits{instance=~\"$Host\"}[5m])",
     "legendFormat": "data_iohits"
    },
    {
     "expr": "rate(node_zfs_arc_prefetch_metadata_iohits{instance=~\"$Host\"}[5m])",
     "legendFormat": "metadata_iohits"
    }
   ]
  },
  { "title": "Misc Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 185 } },
  {
   "title": "Uncached Data",
   "type": "timeseries",
   "description": "Data that intentionally bypasses the ARC if it is sequential reads",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_uncached_size{instance=~\"$Host\"}",
     "legendFormat": "uncached size"
    },
    {
     "expr": "node_zfs_arc_uncached_evictable_data{instance=~\"$Host\"}",
     "legendFormat": "uncached evictable data"
    }
   ]
  },
  {
   "title": "ZFS Prefetch Activity",
   "type": "timeseries",
   "description": "Rate of predictive (sequential stride) and prescient (filesystem-hinted) prefetch operations. High predictive prefetch is expected during media\n  streaming.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 194 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_prescient_prefetch{instance=~\"$Host\"}[5m])",
     "legendFormat": "Prescient"
    },
    {
     "expr": " rate(node_zfs_arc_predictive_prefetch{instance=~\"$Host\"}[5m])",
     "legendFormat": "Predictive"
    }
   ]
  },
  {
   "title": "dmu_tx_dmu_tx - 1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_dmu_tx_dmu_tx_delay{instance=\"$Host\"}",
     "legendFormat": "delay"
    },
    {
     "expr": "node_zfs_dmu_tx_dmu_tx_dirty_delay{instance=\"$Host\"}",
     "legendFormat": "dirty_delay"
    },
    {
     "expr": "node_zfs_dmu_tx_dmu_tx_dirty_over_max{instance=\"$Host\"}",
     "legendFormat": "dirty_over_max"
    },
    {
     "expr": "node_zfs_dmu_tx_dmu_tx_dirty_throttle{instance=\"$Host\"}",
     "legendFormat": "dirty_throttle"
    },
    {
     "expr": "node_zfs_dmu_tx_dmu_tx_error{instance=\"$Host\"}",
     "legendFormat": "error"
    },
    {
     "expr": "node_zfs_dmu_tx_dmu_tx_group{instance=\"$Host\"}",
     "legendFormat": "group"
    },
    {
     "expr": "node_zfs_dmu_tx_dmu_tx_memory_reclaim{instance=\"$Host\"}",
     "legendFormat": "memory_reclaim"
    },
    {
     "expr": "node_zfs_dmu_tx_dmu_tx_memory_reserve{instance=\"$Host\"}",
     "legendFormat": "memory_reserve"
    },
    {
     "expr": "node_zfs_dmu_tx_dmu_tx_quota{instance=\"$Host\"}",
     "legendFormat": "quota"
    },
    {
     "expr": "node_zfs_dmu_tx_dmu_tx_suspended{instance=\"$Host\"}",
     "legendFormat": "suspended"
    }
   ]
  },
  {
   "title": "dmu_tx_dmu_tx - 2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_zfs_dmu_tx_dmu_tx_assigned{instance=\"$Host\"}[5m])",
     "legendFormat": "assigned"
    }
   ]
  },
  {
   "title": "fm",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 215 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_zfs_fm_erpt_dropped{instance=\"$Host\"}[5m])",
     "legendFormat": "erpt_dropped"
    },
    {
     "expr": "rate(node_zfs_fm_erpt_set_failed{instance=\"$Host\"}[5m])",
     "legendFormat": "erpt_set_failed"
    },
    {
     "expr": "rate(node_zfs_fm_fmri_set_failed{instance=\"$Host\"}[5m])",
     "legendFormat": "fmri_set_failed"
    },
    {
     "expr": "rate(node_zfs_fm_payload_set_failed{instance=\"$Host\"}[5m])",
     "legendFormat": "payload_set_failed"
    }
   ]
  },
  {
   "title": "zfetch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 222 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_zfs_zfetch_hits{instance=\"$Host\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(node_zfs_zfetch_misses{instance=\"$Host\"}[5m])",
     "legendFormat": "misses"
    },
    {
     "expr": "rate(node_zfs_zfetch_max_streams{instance=\"$Host\"}[5m])",
     "legendFormat": "max_streams"
    }
   ]
  },
  {
   "title": "zil - bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 229 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_zfs_zil_zil_itx_copied_bytes{instance=\"$Host\"}[5m])",
     "legendFormat": "itx_copied_bytes"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_indirect_bytes{instance=\"$Host\"}[5m])",
     "legendFormat": "itx_indirect_bytes"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_metaslab_normal_bytes{instance=\"$Host\"}[5m])",
     "legendFormat": "itx_metaslab_normal_bytes"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_metaslab_slog_bytes{instance=\"$Host\"}[5m])",
     "legendFormat": "itx_metaslab_slog_bytes"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_needcopy_bytes{instance=\"$Host\"}[5m])",
     "legendFormat": "itx_needcopy_bytes"
    }
   ]
  },
  {
   "title": "zil - count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 236 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_zfs_zil_zil_commit_count{instance=\"$Host\"}[5m])",
     "legendFormat": "commit_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_commit_writer_count{instance=\"$Host\"}[5m])",
     "legendFormat": "commit_writer_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_copied_count{instance=\"$Host\"}[5m])",
     "legendFormat": "itx_copied_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_count{instance=\"$Host\"}[5m])",
     "legendFormat": "itx_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_indirect_count{instance=\"$Host\"}[5m])",
     "legendFormat": "itx_indirect_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_metaslab_normal_count{instance=\"$Host\"}[5m])",
     "legendFormat": "itx_metaslab_normal_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_metaslab_slog_count{instance=\"$Host\"}[5m])",
     "legendFormat": "itx_metaslab_slog_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_needcopy_count{instance=\"$Host\"}[5m])",
     "legendFormat": "itx_needcopy_count"
    }
   ]
  },
  {
   "title": "ZPOOL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 243 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by (zpool) (rate(node_zfs_zpool_dataset_reads{instance=\"$Host\"}[5m]))",
     "legendFormat": "{{zpool}} - rcnt"
    },
    {
     "expr": "sum by (zpool) (rate(node_zfs_zpool_dataset_writes{instance=\"$Host\"}[5m]))",
     "legendFormat": "{{zpool}} - reads"
    },
    {
     "expr": "sum by (zpool) (rate(node_zfs_zpool_dataset_nread{instance=\"$Host\"}[5m])) ",
     "legendFormat": "{{zpool}} - wcnt"
    },
    {
     "expr": "sum by (zpool) (rate(node_zfs_zpool_dataset_nwritten{instance=\"$Host\"}[5m]))",
     "legendFormat": "{{zpool}} - writes"
    }
   ]
  }
 ]
}