---
# tasks file for netmaker role

# Block for main netmaker role
- name: Block for main netmaker role
  tags:
    - netmaker
  block:
    - name: Set iptables policy to FORWARD ACCEPT
      ansible.builtin.iptables:
        chain: FORWARD
        policy: ACCEPT
      become: true

    # For coredns and dns resolution with Netmaker
    # https://docs.netmaker.io/architecture.html#coredns
    - name: Stop and disable systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enabled: false
      become: true

    - name: Create the Netmaker directory
      ansible.builtin.file:
        path: "{{ netmaker_directory }}"
        state: directory
        owner: "{{ default_user }}"
        group: "{{ default_user }}"
        mode: 0766

    # Copy the Netmaker MQ configuration file
    - name: Copy the Netmaker MQ configuration file
      ansible.builtin.copy:
        src: "mosquitto.conf"
        dest: "{{ netmaker_directory }}/mosquitto.conf"
        mode: 0666
      notify: Restart Netmaker

    # Copy the Netmaker wait script
    - name: Copy the Netmaker wait script
      ansible.builtin.copy:
        src: "wait.sh"
        dest: "{{ netmaker_directory }}/wait.sh"
        mode: 0777
      notify: Restart Netmaker

    # Write the Caddyfile
    - name: Write the Caddyfile
      ansible.builtin.template:
        src: Caddyfile.j2
        dest: "{{ netmaker_directory }}/Caddyfile"
        mode: 0666
      when: not netmaker_pro
      notify: Restart Netmaker

    # Write the enterprise Caddyfile
    - name: Write the enterprise Caddyfile
      ansible.builtin.template:
        src: Caddyfile_pro.j2
        dest: "{{ netmaker_directory }}/Caddyfile"
        mode: 0666
      when: netmaker_pro
      notify: Restart Netmaker

    # Write the netmaker environment file
    - name: Write the netmaker environment file
      ansible.builtin.template:
        src: netmaker.env.j2
        dest: "{{ netmaker_directory }}/netmaker.env"
        mode: 0666
      notify: Restart Netmaker

    # Write the  docker-compose file
    - name: Write the docker-compose file
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ netmaker_directory }}/docker-compose.yml"
        mode: 0666
      notify: Restart Netmaker

    # Write the enterprise docker-compose file
    - name: Write the docker-compose.override file (enterprise)
      ansible.builtin.template:
        src: docker-compose-pro.yml.j2
        dest: "{{ netmaker_directory }}/docker-compose.override.yml"
        mode: 0666
      when: netmaker_pro
      notify: Restart Netmaker

    # Remove the enterprise docker-compose file if not ee edition
    - name: Remove the docker-compose.override file (enterprise)
      ansible.builtin.file:
        path: "{{ netmaker_directory }}/docker-compose.override.yml"
        state: absent
      when: not netmaker_pro
      notify: Restart Netmaker
