---
# Install the netclient via systemd.
#
# The hostvars for each host will have a list of networks that the host
# should connect to.
#
# Required input vars:
#   netmaker_enrollment_key_list: The list of enrollment keys from the Netmaker
#                                 server.
#   netmaker_netclient_networks: A list of networks to connect to on the
#                                Netmaker server.

- name: Block for netclient install via systemd
  tags:
    - netmaker
    - netmaker.netclient
    - netmkaer.netclient.systemd
  block:

    # Get the netclient binary and make it executable
    - name: Get the netclient binary
      ansible.builtin.get_url:
        url: "https://github.com/gravitl/netclient/releases/download/\
              {{ netmaker_version }}\
              /netclient-linux-amd64"
        dest: "/sbin/netclient"
        owner: "root"
        group: "root"
        mode: 0755
      become: true
      notify: Restart Netclient systemd

    # Copy the netclient systemd service file
    - name: Copy the netclient systemd service file
      ansible.builtin.copy:
        src: "netclient.service"
        dest: "/etc/systemd/system/netclient.service"
        mode: 0666
      become: true
      notify: Restart Netclient systemd

    # Build a list of networks and tokens to connect to.
    - name: Build a list of networks and tokens to connect to
      ansible.builtin.set_fact:
        netclient_networks: "{{ netclient_networks | default([]) +
                               [{'name': item_hostvar.name,
                                 'tags': item_hostvar.tags,
                                 'token': item_key.token}] }}"
      loop: "{{ netmaker_netclient_networks }}"
      loop_control:
        loop_var: item_hostvar
      vars:
        item_key: "{{ netmaker_enrollment_key_list.stdout | from_json
                      | json_query(query_key) | first }}"
        query_key: "[?contains(tags, `{{ item_hostvar.tags }}`)]"

    # List all connected networks
    - name: List all connected networks
      ansible.builtin.command:
        cmd: "netclient list"
      register: netclient_list_response
      changed_when: false
      become: true

    # Join all the networks
    - name: Join all the networks
      ansible.builtin.command:
        cmd: "netclient join --token={{ item.token }}"
      loop: "{{ netclient_networks }}"
      loop_control:
        loop_var: item
        label: "{{ item.name }}"
      become: true
      changed_when: "item.name not in netclient_list_response.stdout"
      when: "item.name not in netclient_list_response.stdout"
      # notify: Restart Netclient systemd
