---
# Use the NMCTL CLI tool to create enrollment keys on the
# Netmaker server as required.
# The resulting enrollment keys are stored in the Ansible
# fact netmaker_enrollment_key_list.stdout

# Get the current list of enrollment keys
- name: Get the current list of enrollment keys
  ansible.builtin.command:
    cmd: "nmctl enrollment_key list -o json"
  register: netmaker_enrollment_key_list
  changed_when: false

# Create the enrollment key if it doesn't exist
- name: Create the enrollment key if it doesn't exist
  ansible.builtin.command:
    cmd: >
      nmctl enrollment_key create
      --tags="{{ item.tags }}"
      --networks="{{ item.name }}"
      --unlimited={{ item.enrollment_unlimited }}
  loop: "{{ netmaker_networks }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.tags not in netmaker_enrollment_key_list.stdout
  changed_when: item.tags not in netmaker_enrollment_key_list.stdout

# Get the latest enrollment keys
- name: Get the latest enrollment keys
  ansible.builtin.command:
    cmd: "nmctl enrollment_key list -o json"
  register: netmaker_enrollment_key_list
  changed_when: false
