---
# Create a network on the Netmaker server using the NMCTL CLI tool
#
# input vars:
#   item: a single network definition from netmaker_networks
#         variable (see services/netmaker/vars/netmaker.yaml)

- name: Block for creating networks
  tags:
    - netmaker
    - netmaker.network
  block:

    # Create the network on the Netmaker server
    - name: Create the network on the Netmaker server
      ansible.builtin.command:
        cmd: >-
          nmctl network create
           --name="{{ item.name }}"
           --ipv4_addr="{{ item.addressrange }}"
      changed_when: false
