---
# Update a node on the netmaker server using the NMCTL CLI tool
#
# input vars:
#  netmaker_node_definition: a single node_definition to be udpated.

- name: Block for node update
  tags:
    - netmaker
    - netmaker.netclient
    - netmaker.netclient.join
  block:
    # Set ingress state for the node
    - name: Set ingress state for the node
      ansible.builtin.command:
        cmd: >
          nmctl node
          {{ 'create_ingress'
             if netmaker_node_definition.isingressgateway
             else 'delete_ingress' }}
          {{ netmaker_node_definition.network }}
          {{ netmaker_node_definition.id }}
      when: netmaker_node_definition.isingressgateway is defined
      changed_when: false

    # Set egress state for the node
    - name: Set egress state for the node
      ansible.builtin.command:
        cmd: >
          nmctl node
          {{ 'create_egress'
             if netmaker_node_definition.isegressgateway
             else 'delete_egress' }}
          {{ netmaker_node_definition.network }}
          {{ netmaker_node_definition.id }}
          {{ netmaker_node_definition.egressgatewayranges | join(',')
             if netmaker_node_definition.isegressgateway }}
      when: netmaker_node_definition.isegressgateway is defined
      changed_when: false
