---
# Create or update the external client on the Netmaker server
# using the NMCTL CLI tool.
#
# input vars:
#   item: a single external client definition from netmaker_ext_clients
#         variable (see vars/netmaker.yaml)
#   node: the node that is the ingress gateway for the network

# Create or update the external client on the Netmaker server
- name: Create or update the external client on the Netmaker server
  ansible.builtin.command:
    cmd: >-
      nmctl ext_client create "{{ item.network }}" "{{ node.id }}"
       --id="{{ item.name }}"
       --allowedips="{{ item.allowedips }}"
       --dns="{{ item.dns }}"
  changed_when: false
  tags:
    - netmaker
    - netmaker.ext_client
