---
# Install the NMCTL CLI tool for interacting with the Netmaker API
# https://netmaker.readthedocs.io/en/master/nmctl.html#external-clients
#
# input variables:
#  netmaker_check_for_admin: boolean

# Block for netmaker nmctl role
- name: Block for netmaker nmctl role
  tags:
    - netmaker
    - netmaker.nmctl
  block:

    # Get the nmctl binary and make it executable
    - name: Get the nmctl binary
      ansible.builtin.get_url:
        url: "https://github.com/gravitl/netmaker/releases/download/\
              {{ netmaker_version }}\
              /nmctl-linux-amd64"
        dest: "/usr/local/bin/nmctl"
        owner: "{{ default_user }}"
        group: "{{ default_user }}"
        mode: 0755
        # Force the download even if the file already exists so it can be
        # updated if needed.
        force: true
      become: true

    # Create the autocomplete file for zsh for the nmctl binary
    - name: Create the autocomplete file for zsh for the nmctl binary
      ansible.builtin.shell:
        cmd: 'nmctl completion zsh > /usr/share/zsh/vendor-completions/_nmctl'
        creates: '/usr/share/zsh/vendor-completions/_nmctl'
      become: true

    # Create a nmctl context to interact with the Netmaker API
    #
    # The context file is stored in the '~/.netmaker' directory
    - name: Create nmctl context
      ansible.builtin.command:
        cmd: "nmctl context set {{ netmaker_nmctl_context_name }} \
              --endpoint={{ netmaker_nmctl_endpoint }} \
              --master_key={{ secret_nm_master_key }}"
      changed_when: false

    # Set the nmctl context to interact with the Netmaker API
    - name: Set nmctl context
      ansible.builtin.command:
        cmd: "nmctl context use {{ netmaker_nmctl_context_name }}"
      changed_when: false

    # Call the api to see if a super admin user exists
    - name: Check for Netmaker superadmin users
      ansible.builtin.uri:
        url: "https://api.{{ netmaker_base_domain }}/api/users/adm/hassuperadmin"
        method: GET
        status_code: 200
        validate_certs: true
        return_content: true
      register: netmaker_url_check_for_superadmin
      when: "netmaker_check_for_admin"

    # Convert the content to a boolean
    - name: Convert the content to a boolean
      ansible.builtin.set_fact:
        netmaker_has_superadmin: "{{ netmaker_url_check_for_superadmin.content |
                                     from_json }}"
      when: "netmaker_check_for_admin"

    # # Create the Netmaker admin user if it doesn't exist
    # - name: Create the admin user
    #   ansible.builtin.command:
    #     cmd: "nmctl user create \
    #           --name={{ secret_nm_admin_account }} \
    #           --password={{ secret_nm_admin_password }} \
    #           --admin=true"
    #   when: "netmaker_check_for_admin and
    #         not netmaker_has_superadmin"
    #   changed_when: false

    # Create the Netmaker superadmin using the API if it doesn't exist
    - name: Create the superadmin user
      ansible.builtin.uri:
        url: "https://api.{{ netmaker_base_domain }}/api/users/adm/createsuperadmin"
        method: POST
        status_code: 200
        validate_certs: true
        body_format: json
        body:
          username: "{{ secret_nm_admin_account }}"
          password: "{{ secret_nm_admin_password }}"
          confirm-password: "{{ secret_nm_admin_password }}"
      when: "netmaker_check_for_admin and
            not netmaker_has_superadmin"
