---
# This task will copy files or filled out templates to the host for the docker containers
# The input variable is a dictionary with the following keys:
# docker_file:
#   - name: the name of the docker container
#   - src: the source file
#   - dest: the destination file
#   - mode: the mode of the file
#   - container_name: the name of the docker container to restart if the file changes

# Ensure the directory exists
- name: Ensure the directory exists
  ansible.builtin.file:
    path: "{{ docker_file.dest | dirname }}"
    state: directory
    mode: '0755'

- name: Copy file
  ansible.builtin.copy:
    src: "{{ docker_file.src }}"
    dest: "{{ docker_file.dest }}"
    mode: "{{ docker_file.mode }}"
  when: not docker_file.src.endswith('.j2')
  register: docker_copy_results
  notify: Restart docker container

- name: Process template file
  ansible.builtin.template:
    src: "{{ docker_file.src }}"
    dest: "{{ docker_file.dest | regex_replace('\\.j2$', '') }}"
    mode: "{{ docker_file.mode }}"
  when: docker_file.src.endswith('.j2')
  register: docker_template_results
  notify: Restart docker container

# Collect changed container names
- name: Collect changed container names
  ansible.builtin.set_fact:
    docker_containers_to_restart: "{{ docker_containers_to_restart + [docker_file.container_name] }}"
  when: docker_copy_results.changed or docker_template_results.changed
  changed_when: false
