---
# This file will copy files or filled out templates to the host for the docker containers
# The input variable is a dictionary with the following keys:
# file:
#   - name: the name of the docker container
#   - src: the source file
#   - dest: the destination file
#   - mode: the mode of the file
#   - container_name: the name of the docker container to restart if the file changes

# Ensure the directory exists
- name: Ensure the directory exists
  ansible.builtin.file:
    path: "{{ file.dest | dirname }}"
    state: directory
    mode: '0755'

- name: Copy file
  ansible.builtin.copy:
    src: "{{ file.src }}"
    dest: "{{ file.dest }}"
    mode: "{{ file.mode }}"
  when: not file.src.endswith('.j2')
  register: copy_results
  notify: Restart docker container

- name: Process template file
  ansible.builtin.template:
    src: "{{ file.src }}"
    dest: "{{ file.dest | regex_replace('\\.j2$', '') }}"
    mode: "{{ file.mode }}"
  when: file.src.endswith('.j2')
  register: template_results
  notify: Restart docker container

# Collect changed container names
- name: Collect changed container names
  ansible.builtin.set_fact:
    docker_containers_to_restart: "{{ docker_containers_to_restart + [file.container_name] }}"
  when: copy_results.changed or template_results.changed
  changed_when: false
