---
# Setup docker applications when applicable.

# Configure plex when the flag is set
- name: "Configure Plex"
  ansible.builtin.include_role:
    name: plex
  when: plex_setup is defined and plex_setup
  tags:
    - docker
    - docker.compose
    - plex

# Set up logrotate configs for Docker container log files
- name: Set up logrotate configs
  ansible.builtin.include_tasks: setup_logrotate.yaml
  when: docker_logrotate_configs is defined
  tags:
    - docker
    - docker.compose
