---
# main task file for docker role
# inputs:
#   - docker_install: boolean to install docker
#   - docker_config: boolean to configure docker

# install docker
- name: Install docker
  ansible.builtin.include_tasks: install_docker.yaml
  when: docker_install is true
  tags:
    - docker

# copy required docker container configuration files
- name: Copy required docker container configuration files
  ansible.builtin.include_tasks: copy_configuration_files.yaml
  when: docker_config is true
  tags:
    - docker
    - docker.compose

# run the docker compose tasks
- name: Run the docker compose tasks
  ansible.builtin.include_tasks: docker_compose.yaml
  when: docker_config is true
  tags:
    - docker
    - docker.compose

# prune the docker system
- name: Prune everything
  community.docker.docker_prune:
    containers: true
    images: true
    networks: true
    volumes: true
    builder_cache: true
  become: true
  tags:
    - docker
    - docker.prune
