---
# tasks file for base
#
# inputs:
#   - base_additonal_packages: list of additional packages to install
#   - base_dotfiles: dictionary of dotfiles configuration

# Update and upgrade apt packages
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    cache_valid_time: 3600
  become: true

# install base packages on the host
- name: Install base packages
  ansible.builtin.apt:
    # append the list of packages to install with optional additional packages
    name: "{{ base_packages + (base_additional_packages | default([])) }}"
    state: present
  become: true

# Check if a reboot is required
- name: Check if a reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: base_reboot_required_file

# Reboot the host if a reboot is required
- name: Reboot the host if a reboot is required
  ansible.builtin.reboot:
  when: base_reboot_required_file.stat.exists
  become: true

# install docker when the flag is set
- name: Install docker
  ansible.builtin.include_tasks: setup_docker.yaml
  when: install_docker is true

# setup dotfiles when the flag is set
- name: Setup dotfiles
  ansible.builtin.include_tasks: setup_dotfiles.yaml
  when: base_dotfiles['install'] is true

# flush all handlers
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
