---
# tasks file for base
#
# inputs:
#   - base_additional_packages: list of additional packages to install
#   - base_additional_services: list of additional services to enable and start
#   - base_reboot_host_if_required: boolean to reboot the host if required
#   - base_apt_upgrade_packages: if or how to upgrade apt packages
#   - base_apt_update_packages: boolean to update apt packages or skip
#   - base_docker_install: boolean to install docker
#   - base_dotfiles: dictionary of dotfiles configuration
#   - base_user_run_setup: boolean to setup a user
#   - base_postfix: dictionary of postfix configuration
#   - base_timezone: timezone to set


# Update and upgrade apt packages
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: "{{ base_apt_upgrade_packages }}"
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: base_apt_update_packages is true
  tags:
    - base
    - base.apt

# install base packages on the host
- name: Install base packages
  ansible.builtin.apt:
    # append the list of packages to install with optional additional packages
    name: "{{ base_packages + (base_additional_packages | default([])) }}"
    state: present
  become: true
  tags:
    - base
    - base.apt

# set the timezone
- name: Set the timezone
  community.general.timezone:
    name: "{{ base_timezone }}"
  become: true
  tags:
    - base
    - base.timezone

# Check if a reboot is required
- name: Check if a reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: base_reboot_required_file
  when: base_reboot_host_if_required is true
  tags:
    - base

# Reboot the host if a reboot is required
- name: Reboot the host if a reboot is required
  ansible.builtin.reboot:
  when:
    base_reboot_host_if_required is true and
    base_reboot_required_file.stat.exists
  become: true
  tags:
    - base

# setup the user when the flag is set
- name: Setup the user
  ansible.builtin.include_tasks: setup_user.yaml
  when: base_user_run_setup is true
  tags:
    - base
    - base.user

# install docker when the flag is set
- name: Install docker
  ansible.builtin.import_role:
    name: docker
  vars:
    docker_install: "{{ base_docker_install }}"
    docker_config: "{{ base_docker_config }}"
  when: base_docker_install is true
  tags:
    - base
    - base.docker
    - docker

# setup dotfiles when the flag is set
- name: Setup dotfiles
  ansible.builtin.include_tasks: setup_dotfiles.yaml
  when: base_dotfiles['install'] is true
  tags:
    - base
    - base.dotfiles

# set specified systemd services to the specified state and status
- name: Set specified systemd services to the specified state and status
  ansible.builtin.service:
    name: "{{ service.name }}"
    state: "{{ service.state }}"
    enabled: "{{ service.enabled | default(true) }}"
  loop: "{{ base_services + (base_additional_services | default([])) }}"
  loop_control:
    loop_var: service
    label: "{{ service.name }}"
  become: true
  when: ansible_os_family == "Debian"
  notify: Systemctl reset-failed
  tags:
    - base
    - base.services

# setup postfix when the flag is set
- name: Setup postfix
  ansible.builtin.include_tasks: setup_postfix.yaml
  when: base_postfix['install'] is true
  tags:
    - base
    - base.postfix

# flush all handlers
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - base
