---
# tasks to setup docker on a host.

# install docker
- name: Install docker
  ansible.builtin.apt:
    pkg:
      - docker.io
      - docker-compose
    state: present
  become: true

# add the user to the docker group
- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ default_user }}"
    groups: docker
    append: true
  become: true
  notify: Restart docker

# create the docker data and config directories
- name: Create docker data and config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ docker_data_dir }}"
    - /etc/docker
  become: true

# create the docker daemon config file
- name: Create docker daemon config file
  ansible.builtin.copy:
    content: "{{ docker_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: 0644
  when: docker_daemon_options.keys() | length > 0
  become: true
  notify: Restart docker
