---
# tasks to setup a user on a host.
#
# Creates the user and adds the public ssh keys to the user.

# inputs:
#   - base_user_default: default user to setup
#   - base_user_password_prehashed: default user password prehashed
#   - base_user_additional_groups: additional user groups to be added to
#     base_user_add_ssh_keys: boolean to add ssh keys to the user


# block for base user tasks
- name: Block for base user tasks
  tags:
    - base
    - base.user
  block:
    # create the default user
    - name: Create the default user
      ansible.builtin.user:
        name: "{{ base_user_default }}"
        password: "{{ base_user_password_prehashed }}"
        update_password: on_create
        createhome: true
        home: "/home/{{ base_user_default }}"
        groups: "{{ base_user_groups + (base_user_additional_groups | default([])) }}"  # yamllint disable-line rule:line-length
        state: present
        generate_ssh_key: true
        ssh_key_type: ed25519
      become: true

    # Add the public ssh keys to the user
    - name: Add the public ssh keys to the user
      ansible.posix.authorized_key:
        user: "{{ base_user_default }}"
        state: present
        key: "{{ item.key }}"
        comment: "{{ item.name }}"
      loop: "{{ secret_ssh_keys }}"
      loop_control:
        label: "{{ item.name }}"
      when: base_user_add_ssh_keys is true
