---
# Wait for any unattended upgrades to finish.
- name: Wait for any possibly running unattended upgrade to finish.
  ansible.builtin.shell:
    cmd: >
      systemd-run --property="After=apt-daily.service apt-daily-upgrade.service"
      --wait /bin/true
  become: true
  changed_when: false

# Sleep for 2 seconds to allow the unattended upgrade to finish.
- name: Sleep for 2 seconds to allow the unattended upgrade to finish.
  ansible.builtin.wait_for:
    timeout: 2
  changed_when: false
