---
# Apply base updates to all hosts:

- name: Apply base updates to all hosts
  hosts: all
  vars_files:
    - ../vault/vault.yaml
  roles:
    - role: base
  tags:
    - base
    - base.apt
    - base.services

  tasks:
    # update pihole
    - name: Update pihole
      ansible.builtin.include_role:
        name: pihole
        tasks_from: update_pihole.yaml
      when: inventory_hostname in groups['pihole']
      tags:
        - pihole

    # Configure the Proxmox repos
    - name: Configure the Proxmox repos
      ansible.builtin.include_role:
        name: proxmox
        tasks_from: pve_repos
      when: inventory_hostname in groups['proxmox_nodes']
