---
# Apply docker compose updates to docker hosts

- name: Apply docker compose updates to docker hosts
  hosts: docker_hosts
  vars_files:
    - ../vault/vault.yaml
  roles:
    - role: docker
      vars:
        docker_install: "{{ base_docker_install }}"
        docker_config: "{{ base_docker_config }}"
  tags:
    - docker
    - docker.compose
    - docker.prune
