---
# Update dotfiles on all hosts

- name: Update dotfiles on all hosts
  hosts: all
  vars_files:
    - ../vault/vault.yaml


  tasks:
    - name: Update dotfiles
      ansible.builtin.include_role:
        name: base
        tasks_from: setup_dotfiles.yaml
      when: base_dotfiles['install'] is true
      tags:
        - base
        - base.dotfiles
