---
# Configure hosts using the base role
#
# This task assumes the hosts have all been created and are accessible and ready to be configured.
# Defaults to all hosts but can be overridden


# Run the first time setup to configure the hosts
- name: Run the first time setup to configure hosts
  hosts: all
  vars_files:
    - ../vault/vault.yaml
  tags:
    - base
    - tailscale
    - tailscale.install

  tasks:
    # Run the pihole role
    - name: Import pihole role
      ansible.builtin.import_role:
        name: pihole
        tasks_from: install_pihole_v6
      when:
        hostvars[inventory_hostname].pihole_setup is defined and
        hostvars[inventory_hostname].pihole_setup is true
      tags:
        - pihole

    # Run the fileserver role
    - name: Import fileserver role
      ansible.builtin.import_role:
        name: fileserver
      when:
        hostvars[inventory_hostname].fileserver_setup is defined and
        hostvars[inventory_hostname].fileserver_setup is true
      tags:
        - fileserver
        - fileserver.nfs-server
        - fileserver.nfs-client
        - fileserver.mergerfs
        - fileserver.ext4
        - fileserver.snapraid
        - fileserver.zfs
        - fileserver.swap

    # Run the sanoid role
    - name: Import sanoid role
      ansible.builtin.import_role:
        name: sanoid
      when:
        hostvars[inventory_hostname].sanoid_setup is defined and
        hostvars[inventory_hostname].sanoid_setup is true
      tags:
        - sanoid

    # Run the base role
    - name: Import base role
      ansible.builtin.import_role:
        name: base
      vars:
        base_postfix: "{{ hostvars[inventory_hostname].postfix }}"
      tags:
        - base
        - base.apt
        - base.docker
        - base.dotfiles
        - base.known_hosts
        - base.postfix
        - base.timezone

    # Run the geerlingguy.security role
    - name: Import geerlingguy.security role
      ansible.builtin.import_role:
        name: geerlingguy.security
      become: true
      tags:
        - base.geerlingguy.security

    # Run the tailscale role
    - name: Import tailscale role
      ansible.builtin.import_role:
        name: tailscale
      when:
        hostvars[inventory_hostname].tailscale_setup is defined and
        hostvars[inventory_hostname].tailscale_setup is true
      tags:
        - tailscale

    # Run the ntfy role
    - name: Import ntfy role
      ansible.builtin.import_role:
        name: ntfy
      when:
        hostvars[inventory_hostname].ntfy_setup is defined and
        hostvars[inventory_hostname].ntfy_setup is true
      tags:
        - ntfy

    # Run the healthchecks role
    - name: Import healthchecks role
      ansible.builtin.import_role:
        name: healthchecks
      when:
        hostvars[inventory_hostname].hc_container_setup is defined and
        hostvars[inventory_hostname].hc_container_setup is true
      tags:
        - healthchecks
