---
# tasks file for cloudflare
#
# inputs:
#   - cloudflare_ip_address: the ip address of the dns record
#   - cloudflare_records: the dns record to update

# Set a Cloudflare A record
# The 'solo' parameter is 'yes' if the state is 'present'. Othwerwise omitted.
- name: Set Cloudflare A record
  community.general.cloudflare_dns:
    zone: "{{ cf_item.zone }}"
    record: "{{ cf_item.record }}"
    type: A
    value: "{{ cloudflare_ip_address }}"
    proxied: "{{ cf_item.proxied | default(false) }}"
    ttl: "{{ cf_item.ttl | default(1) }}"
    state: "{{ cf_item.state | default('present') }}"
    solo: "{{ (cf_item.state == 'present') | ternary('yes', omit) }}"
    api_token: "{{ secret_cf_token }}"
  loop: "{{ cloudflare_records }}"
  loop_control:
    loop_var: cf_item
  tags:
    - cloudflare
    - cloudflare.dns
