---
# tasks file for cloudflare

# Set a Cloudflare A record
# The 'solo' parameter is 'yes' if the state is 'present'. Othwerwise omitted.
- name: Set Cloudflare A record
  community.general.cloudflare_dns:
    zone: "{{ item.zone }}"
    record: "{{ item.record }}"
    type: A
    value: "{{ ip_address }}"
    proxied: "{{ item.proxied | default(false) }}"
    ttl: "{{ item.ttl | default(1) }}"
    state: "{{ item.state | default('present') }}"
    solo: "{{ (item.state == 'present') | ternary('yes', omit) }}"
    api_token: "{{ secret_cf_token }}"
  loop: "{{ netmaker_cf_record }}"
