---
# group_vars for the all group
ansible_become_password: "{{ secret_become_pass }}"

# Default user values
default_user: "nelson"
default_user_email: "nstoik@stechsolutions.ca"
# secret_user_password is set in vars\vault.yaml

# timezone
base_timezone: "America/Edmonton"

known_hosts_ansible_file: "/home/{{ default_user }}/.ssh/known_hosts_ansible"

# smtp variables
smtp_host: "smtp.mailgun.org"
smtp_port: 587

# ntfy variables
ntfy_base_url: "https://ntfy.stechsolutions.ca"
ntfy_user: "{{ default_user }}"
ntfy_email_user: "ntfy@mg.stechsolutions.ca"

# prometheus variables
prometheus_domain: "prometheus.home.stechsolutions.ca"
prometheus_base_url: "https://{{ prometheus_domain }}"

# alertmanager variables
alertmanager_domain: "alertmanager.home.stechsolutions.ca"
alertmanager_base_url: "https://{{ alertmanager_domain }}"

# ntfy-alertmanager variables
ntfy_alertmanager_domain: "ntfy-alertmanager.home.stechsolutions.ca"
ntfy_alertmanager_base_url: "https://{{ ntfy_alertmanager_domain }}"

# geerlingguy.security role variables
# https://galaxy.ansible.com/geerlingguy/security
security_ssh_port: 22
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"
security_sshd_state: started
security_ssh_restart_handler_state: restarted
security_ssh_allowed_users: ["{{ default_user }}"]
security_ssh_allowed_groups: []

security_sudoers_passwordless: []
security_sudoers_passworded: ["{{ default_user }}"]

security_autoupdate_enabled: true
security_autoupdate_blacklist: []

# Autoupdate mail settings used on Debian/Ubuntu only.
security_autoupdate_reboot: true
security_autoupdate_reboot_time: "03:00"
security_autoupdate_mail_to: "{{ default_user_email }}"
security_autoupdate_mail_on_error: true

security_fail2ban_enabled: true
security_fail2ban_custom_configuration_template: "jail.local.j2"
