# This file is used to override the default variables for the netclients_manual
# group.
---

# These hosts need to use a ssh jump host to proxy their connections
ansible_ssh_common_args: >
  -o ProxyCommand='ssh
  -o StrictHostKeyChecking=no
  -W %h:%p nelson@netmaker.stechsolutions.ca'
