---
# group_vars for the proxmox_nodes group
#
# There are some variables that are specific to each node (eg. UPS),
# and those are defined in the host_vars files for each node.

ansible_become_password: "{{ secret_become_pass }}"

# The proxmox nodes need sudo to be installed
host_additional_packages:
  - "sudo"
  - "lshw"
  - "prometheus-node-exporter"

# Use apt dist-upgrade on proxmox nodes
# see https://pve.proxmox.com/pve-docs/chapter-sysadmin.html
base_apt_upgrade_packages: "dist"

# don't automatically reboot the proxmox nodes. Rebooting should be done
# either explicitly or manually.
base_reboot_host_if_required: false

# override some default geerlingguy.security role variables
# for proxmox nodes
security_autoupdate_enabled: false
security_autoupdate_reboot: false
security_ssh_permit_root_login: "yes"
security_ssh_password_authentication: "yes"
security_ssh_allowed_users:
  - "{{ default_user }}"
  - "root"

# Whether to configure the NUT role for the Proxmox nodes
# Default to false, but set to true on the host_vars files of the hosts that have a UPS
proxmox_nut_configure: false

# Proxmox cloud images
# state: present, absent, recreate
proxmox_cloud_imgs:
  # yamllint disable-line rule:line-length
  - url: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img"
    template_name: "ubuntu-22.04-server-cloudimg"
    id: 9000
    state: "present"
    # List of proxmox nodes to download the cloud image to
    proxmox_nodes: "{{ groups['proxmox_nodes'] }}"
  # yamllint disable-line rule:line-length
  - url: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    template_name: "ubuntu-24.04-server-cloudimg"
    id: 9001
    state: "recreate"
    # List of proxmox nodes to download the cloud image to
    proxmox_nodes: "{{ groups['proxmox_nodes'] }}"

# Proxmox container images
proxmox_container_imgs:
  - image: "ubuntu-24.04-standard_24.04-2_amd64.tar.zst"
    proxmox_nodes: "{{ groups['proxmox_nodes'] }}"

# Proxmox Permissions and ACLs
proxmox_groups:
  - name: "Admins"
    comment: "Admins group"
    state: "present"
    permissions:
      - path: "/"
        role: "Administrator"
        entity: "group"
        identifier: "Admins"
  - name: "API_RO_Users"
    comment: "API Read-Only Users group"
    state: "present"
    permissions:
      - path: "/"
        role: "PVEAuditor"
        entity: "group"
        identifier: "API_RO_Users"

proxmox_users:
  - userid: "{{ default_user }}@pam"
    comment: "Primary user"
    email: "{{ default_user_email }}"
    groups: "Admins"
    state: "present"
  - userid: "prometheus@pve"
    comment: "Prometheus user"
    email: "noemmail@noemail.com"
    groups: "API RO Users"
    state: "present"
    password: "{{ secret_pve_prometheus_user_password }}"
  - userid: "homepage@pve"
    comment: "Homepage user"
    email: "noemail@noemail.com"
    groups: "API_RO_Users"
    state: "present"
    password: "{{ secret_pve_homepage_user_password }}"

proxmox_notification_targets:
  - name: ntfy-info
    method: get
    url: "https://ntfy.stechsolutions.ca/Proxmox/trigger"
    priority: 2
    comment: "Proxmox info notifications"
    token_name: Proxmox
  - name: ntfy-error
    method: get
    url: "https://ntfy.stechsolutions.ca/Proxmox/trigger"
    priority: 5
    comment: "Proxmox error notifications"
    token_name: Proxmox

proxmox_notification_matchers:
  - name: ntfy-info-match
    comment: "Proxmox info notifications matcher"
    mode: all
    target: ntfy-info
    match-severity: "info"
  - name: ntfy-error-match
    comment: "Proxmox error notifications matcher"
    mode: all
    target: ntfy-error
    match-severity: "notice,warning,error,unknown"

# Proxmox backup configs
proxmox_backups:
  - id: "backup-daily"
    comment: "Daily backup of all VMs"
    storage: "pbs"
    schedule: "04:30"
    repeat-missed: true
    all: true

# Proxmox ACME configuration
proxmox_acme:
  # Proxmox ACME account
  account:
    name: "default"
    contact: "{{ default_user_email }}"
    directory: "https://acme-v02.api.letsencrypt.org/directory"

  # Domain names for the ACME account
  domains:
    - "pve3.home.stechsolutions.ca"

  # Proxmox ACME plugin
  plugin:
    type: "dns"
    id_name: "cf"
    cf_api_email: "{{ default_user_email }}"
    cf_api_key: "{{ secret_cf_token }}"
