---
# group_vars for the proxmox_vms group
ansible_become_password: "{{ secret_become_pass }}"

host_additional_packages:
  - "qemu-guest-agent"
  - prometheus-node-exporter

host_additional_services:
  - name: "qemu-guest-agent.service"
    state: "started"
    enabled: true
  - name: "openipmi.service"
    state: "stopped"
    enabled: false
