---
# group_vars for the proxmox_vms group
ansible_become_password: "{{ secret_become_pass }}"

proxmox_vm_additonal_packages:
  - "qemu-guest-agent"
proxmox_vm_additional_services:
  - "qemu-guest-agent.service"
