---
name: Ansible Lint

on: [push, pull_request]  # yamllint disable-line rule:truthy

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run yammlint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint
          file_or_dir: .

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
