---
name: Ansible Lint

on: [push, pull_request]  # yamllint disable-line rule:truthy

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint
          file_or_dir: .

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main

      - name: Create vault_password.txt
        run: |
          pwd
          echo ${{ secrets.ANSIBLE_VAULT_PASSWORD }} > ./vault_pass.txt
          ls

      - name: Run ansible syntax check
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: site.yaml
          options: |
            --syntax-check
