---
name: Ansible Lint

on: [push, pull_request]  # yamllint disable-line rule:truthy

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip3 install ansible-core ansible-lint==6.11 yamllint
          ansible-galaxy install -r requirements.yaml

      - name: Create vault_pass.txt
        run: echo ${{ secrets.ANSIBLE_VAULT_PASSWORD }} > ./vault_pass.txt

      - name: Run yammlint
        run: yamllint .

      - name: Run ansible-lint
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: ansible-lint

      - name: Run ansible-playbook --syntax-check
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: ansible-playbook --syntax-check site.yaml
