---
# Update CNAME entries to Pi-hole

# Ensure that the required directories exist
- name: Ensure that the required directories exist
  ansible.builtin.file:
    path: "{{ pihole_dnsmasq_dir }}"
    state: directory
    mode: 0755
  become: true
  tags:
    - pihole
    - pihole.cname

# Write the cname template file
- name: Write the cname template file
  ansible.builtin.template:
    src: cname.conf.j2
    dest: "{{ pihole_dnsmasq_dir }}/{{ pihole_dnsmasq_file }}"
    mode: 0644
  become: true
  tags:
    - pihole
    - pihole.cname
  notify:
    - Restart pihole
